const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'});
  const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
  const pageErrors=[];page.on('pageerror',error=>pageErrors.push(error.message));
  await page.addInitScript(()=>{
    const books=Array.from({length:8},(_,index)=>({id:'book-'+index,name:['Uzun Vadeli Yatırım Portföyü','Türk Lirası Temettü Portföyü','Amerika Teknoloji Hisseleri','Çocuk Eğitim Portföyü','Emeklilik Birikimleri','Kısa Vadeli Nakit','Altın Ve Fonlar','Deneme Portföyü'][index],positions:[],cashBalances:[],createdAt:new Date().toISOString()}));
    localStorage.setItem('finans-grafigi-portfolios-v2',JSON.stringify(books));
    localStorage.setItem('finans-grafigi-active-portfolio','book-0');
  });
  await page.route('**/api/**',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"test"}'}));
  await page.goto('http://127.0.0.1:8766/',{waitUntil:'domcontentloaded'});
  await page.click('#mobilePortfolioNav');
  await page.waitForTimeout(100);
  const tops=await page.locator('.portfolio-book-tab').evaluateAll(items=>items.map(item=>Math.round(item.getBoundingClientRect().top)));
  assert.ok(new Set(tops).size>1,'Portföy kısayolları mobilde birden çok satıra geçmeli');
  const first=page.locator('.portfolio-book-tab').first(),target=page.locator('.portfolio-book-tab').nth(1);
  const from=await first.boundingBox(),to=await target.boundingBox();
  await page.mouse.move(from.x+from.width/2,from.y+from.height/2);await page.mouse.down();
  await page.waitForTimeout(500);
  assert.equal(await page.locator('.portfolio-book-drag-ghost').count(),1,'Uzun basınca sürükleme gölgesi görünmeli');
  await page.mouse.move(to.x+to.width/2,to.y+to.height/2,{steps:8});
  await page.mouse.up();
  await page.waitForTimeout(100);
  const savedOrder=await page.evaluate(()=>JSON.parse(localStorage.getItem('finans-grafigi-portfolios-v2')).map(item=>item.id));
  assert.notEqual(savedOrder[0],'book-0','Sürükleme portföy sırasını kalıcı değiştirmeli');
  await page.click('#mobileMoreNav');
  await page.selectOption('#layoutDensitySelect','compact');
  await page.selectOption('#fontSizeSelect','large');
  await page.selectOption('#priceDecimalsSelect','4');
  await page.reload({waitUntil:'domcontentloaded'});
  assert.equal(await page.evaluate(()=>document.documentElement.dataset.density),'compact');
  assert.equal(await page.evaluate(()=>document.documentElement.dataset.fontSize),'large');
  assert.equal(await page.evaluate(()=>localStorage.getItem('finans-grafigi-price-decimals')),'4');
  await page.setViewportSize({width:1280,height:900});
  await page.click('#desktopMoreNav');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true,'Masaüstü ayarlar ekranında yatay taşma olmamalı');
  assert.ok((await page.locator('#diagnosticsList dd').count())>=6,'Tanılama kartı temel bağlantı bilgilerini göstermeli');
  assert.deepEqual(pageErrors,[],'Sayfada yakalanmamış JavaScript hatası olmamalı');
  await browser.close();
  console.log('v6.6 mobil portföy ve ayar tarayıcı testi başarılı.');
})().catch(error=>{console.error(error);process.exit(1)});
