const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'});
  const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
  const pageErrors=[];page.on('pageerror',error=>pageErrors.push(error.message));
  await page.addInitScript(()=>{
    const books=Array.from({length:8},(_,index)=>({id:'book-'+index,name:['Uzun Vadeli Yatırım Portföyü','Türk Lirası Temettü Portföyü','Amerika Teknoloji Hisseleri','Çocuk Eğitim Portföyü','Emeklilik Birikimleri','Kısa Vadeli Nakit','Altın Ve Fonlar','Deneme Portföyü'][index],positions:[],cashBalances:[],createdAt:new Date().toISOString()}));
    if(!localStorage.getItem('finans-grafigi-portfolios-v2'))localStorage.setItem('finans-grafigi-portfolios-v2',JSON.stringify(books));
    if(!localStorage.getItem('finans-grafigi-active-portfolio'))localStorage.setItem('finans-grafigi-active-portfolio','book-0');
  });
  await page.route('**/api/**',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"test"}'}));
  await page.goto('http://127.0.0.1:8766/',{waitUntil:'domcontentloaded'});
  await page.click('#mobilePortfolioNav');
  await page.waitForTimeout(420);
  const tops=await page.locator('.portfolio-book-tab').evaluateAll(items=>items.map(item=>Math.round(item.getBoundingClientRect().top)));
  assert.ok(new Set(tops).size>1,'Portföy kısayolları mobilde birden çok satıra geçmeli');
  const first=page.locator('.portfolio-book-tab').first(),target=page.locator('.portfolio-book-tab').nth(4);
  const from=await first.boundingBox(),to=await target.boundingBox();
  await page.mouse.move(from.x+from.width/2,from.y+from.height/2);await page.mouse.down();
  await page.waitForTimeout(500);
  assert.equal(await page.locator('.portfolio-book-drag-ghost').count(),1,'Uzun basınca sürükleme gölgesi görünmeli');
  await page.mouse.move(to.x+to.width/2,to.y+to.height/2,{steps:8});
  await page.waitForTimeout(280);
  await page.mouse.up();
  await page.waitForTimeout(420);
  const savedOrder=await page.evaluate(()=>JSON.parse(localStorage.getItem('finans-grafigi-portfolios-v2')).map(item=>item.id));
  assert.notEqual(savedOrder[0],'book-0','Sürükleme portföy sırasını kalıcı değiştirmeli');
  await page.click('#mobileMoreNav');
  const notificationLayout=await page.locator('.setting-switch').first().evaluate(label=>{const control=label.querySelector('input'),labelBox=label.getBoundingClientRect(),controlBox=control.getBoundingClientRect();return{display:getComputedStyle(label).display,labelCenter:labelBox.top+labelBox.height/2,controlCenter:controlBox.top+controlBox.height/2,controlRight:Math.round(controlBox.right),labelRight:Math.round(labelBox.right)}});
  assert.equal(notificationLayout.display,'flex','Bildirim satırı genel label grid kuralı tarafından ezilmemeli');
  assert.ok(Math.abs(notificationLayout.labelCenter-notificationLayout.controlCenter)<2,'Bildirim anahtarı metinle aynı satırda olmalı');
  assert.ok(Math.abs(notificationLayout.labelRight-notificationLayout.controlRight)<2,'Bildirim anahtarı satırın sağ kenarına yaslanmalı');
  await page.selectOption('#baseCurrencySelect','TRY');
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('finans-grafigi-portfolios-v2')).every(item=>item.displayCurrency==='TRY')),true,'Tercih edilen para birimi bütün portföylere uygulanmalı');
  await page.click('#mobilePortfolioNav');await page.waitForTimeout(220);await page.locator('[data-book-id="book-1"]').click();
  await page.click('#portfolioCurrencyToggle');await page.waitForTimeout(120);
  const localPortfolioCurrencies=await page.evaluate(()=>JSON.parse(localStorage.getItem('finans-grafigi-portfolios-v2')).map(item=>({id:item.id,currency:item.displayCurrency})));
  assert.equal(localPortfolioCurrencies.find(item=>item.id==='book-1').currency,'USD','Aktif portföy düğmesi yalnız seçilen portföyü USD yapmalı');
  assert.equal(localPortfolioCurrencies.filter(item=>item.id!=='book-1').every(item=>item.currency==='TRY'),true,'Aktif portföy düğmesi diğer portföylere dokunmamalı');
  assert.equal(await page.evaluate(()=>localStorage.getItem('finans-grafigi-base-currency')),'TRY','Aktif portföy düğmesi genel tercihi değiştirmemeli');
  await page.click('#allPortfolioCurrencyToggle');await page.waitForTimeout(120);
  assert.equal(await page.evaluate(()=>localStorage.getItem('finans-grafigi-all-portfolio-currency')),'USD','Toplam Portföy düğmesi yalnız birleşik toplam görünümünü değiştirmeli');
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('finans-grafigi-portfolios-v2')).find(item=>item.id==='book-1').displayCurrency),'USD','Toplam Portföy düğmesi aktif portföy seçimini değiştirmemeli');
  await page.click('#portfolioTotalMode');await page.waitForTimeout(120);
  const toolbarPosition=await page.locator('.portfolio-view-toolbar').evaluate(toolbar=>{const card=toolbar.closest('#allPortfolioHead').getBoundingClientRect(),box=toolbar.getBoundingClientRect();return{inside:Boolean(toolbar.closest('#allPortfolioHead')),top:Math.round(box.top-card.top),right:Math.round(card.right-box.right)}});
  assert.equal(toolbarPosition.inside,true,'Üç yeni düğme Toplam Portföy kartının içinde olmalı');
  assert.ok(toolbarPosition.top<=12&&toolbarPosition.right<=12,'Üç yeni düğme Toplam Portföy kartının sağ üstüne hizalanmalı');
  assert.equal(await page.evaluate(()=>localStorage.getItem('finans-grafigi-portfolio-metrics-mode')),'total','Toplam görünümü cihazda saklanmalı');
  assert.equal(await page.locator('#portfolioTotalMode').getAttribute('aria-pressed'),'true','Toplam düğmesi seçili görünmeli');
  await page.evaluate(()=>{document.getElementById('portfolioTotalValue').textContent='₺123,45'});
  await page.click('#portfolioPrivacyToggle');
  const privacyState=await page.locator('#portfolioTotalValue').evaluate(value=>({privateView:value.closest('#portfolioView').classList.contains('is-private'),color:getComputedStyle(value).color,mask:getComputedStyle(value,'::after').content}));
  assert.equal(privacyState.privateView,true,'Gizlilik düğmesi portföy sayfasını özel moda almalı');
  assert.equal(privacyState.mask,'"*****"','Gizli finansal değerlerin yerine beş yıldız görünmeli');
  assert.equal(await page.evaluate(()=>localStorage.getItem('finans-grafigi-portfolio-privacy')),'true','Gizlilik seçimi cihazda saklanmalı');
  await page.click('#mobileMoreNav');
  assert.equal(await page.locator('#baseCurrencySelect').inputValue(),'TRY','Para birimi tercihi diğer portföylerde aynı kalmalı');
  await page.selectOption('#baseCurrencySelect','USD');
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('finans-grafigi-portfolios-v2')).every(item=>item.displayCurrency==='USD')),true,'Yeni tercih bütün portföylere hemen kaydedilmeli');
  assert.equal(await page.evaluate(()=>localStorage.getItem('finans-grafigi-all-portfolio-currency')),'USD','Yeni tercih Toplam Portföy seçiminin üzerine yazmalı');
  await page.selectOption('#fontSizeSelect','large');
  await page.selectOption('#priceDecimalsSelect','4');
  await page.reload({waitUntil:'domcontentloaded'});
  assert.equal(await page.evaluate(()=>document.documentElement.dataset.fontSize),'large');
  assert.equal(await page.evaluate(()=>localStorage.getItem('finans-grafigi-price-decimals')),'4');
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('finans-grafigi-portfolios-v2')).every(item=>item.displayCurrency==='USD')),true,'Genel para birimi tercihi yenilemeden sonra korunmalı');
  assert.equal(await page.evaluate(()=>localStorage.getItem('finans-grafigi-portfolio-metrics-mode')),'total','Toplam görünümü yenilemeden sonra korunmalı');
  assert.equal(await page.evaluate(()=>document.getElementById('portfolioView').classList.contains('is-private')),true,'Gizlilik görünümü yenilemeden sonra korunmalı');
  await page.setViewportSize({width:1280,height:900});
  await page.click('#desktopMoreNav');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true,'Masaüstü ayarlar ekranında yatay taşma olmamalı');
  assert.ok((await page.locator('#diagnosticsList dd').count())>=6,'Tanılama kartı temel bağlantı bilgilerini göstermeli');
  assert.deepEqual(pageErrors,[],'Sayfada yakalanmamış JavaScript hatası olmamalı');
  await browser.close();
  console.log('v6.8 portföy gizlilik ve dönem mobil tarayıcı testi başarılı.');
})().catch(error=>{console.error(error);process.exit(1)});
