const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');

const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const priceApi=fs.readFileSync(path.join(root,'api','price.js'),'utf8');
const fundamentalsApi=fs.readFileSync(path.join(root,'api','fundamentals.js'),'utf8');
const dividendsApi=fs.readFileSync(path.join(root,'api','dividends.js'),'utf8');
const logoSvg=fs.readFileSync(path.join(root,'assets','ozer-finans-mark.svg'),'utf8');

function extractFunction(source,name){
  const start=source.indexOf('function '+name);
  assert.notEqual(start,-1,name+' bulunamadı');
  const brace=source.indexOf('{',start);
  let depth=0;
  for(let index=brace;index<source.length;index++){
    if(source[index]==='{')depth++;
    if(source[index]==='}'){
      depth--;
      if(depth===0)return source.slice(start,index+1);
    }
  }
  throw new Error(name+' kapanış parantezi bulunamadı');
}

const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(match=>match[1]).filter(Boolean);
scripts.forEach((script,index)=>assert.doesNotThrow(()=>new Function(script),'İstemci betiği '+(index+1)+' sözdizimi'));
assert.doesNotThrow(()=>new Function('module','exports','require',priceApi),'Fiyat API sözdizimi');
assert.doesNotThrow(()=>new Function('module','exports','require',fundamentalsApi),'Temel veri API sözdizimi');
assert.doesNotThrow(()=>new Function('module','exports','require',dividendsApi),'Temettü API sözdizimi');

const clientFunctions=['fillMissingRates','calculateRsi','sma','calculatePeriodSummary','normalizePerformance','resultPriceValues','commonPerformanceWindow','isPortfolioSummaryComplete'].map(name=>extractFunction(scripts[0],name)).join('\n');
const {fillMissingRates,calculateRsi,sma,calculatePeriodSummary,resultPriceValues,commonPerformanceWindow,isPortfolioSummaryComplete}=new Function(clientFunctions+';return {fillMissingRates,calculateRsi,sma,calculatePeriodSummary,resultPriceValues,commonPerformanceWindow,isPortfolioSummaryComplete};')();

assert.deepEqual(fillMissingRates([null,null,2,null,3,null]),[null,null,2,2,3,3],'Gelecekteki kur geçmişe taşınmamalı');
assert.deepEqual(sma([null,1,2,3],3),[null,null,null,2],'Eksik değer içeren MA penceresi hesaplanmamalı');
const rsi=calculateRsi([1,2,3,2,4,5,4,6,7,8,7,9,10,11,12,13,14,13,15,16],14);
assert.ok(Number.isFinite(rsi.at(-1))&&rsi.at(-1)>=0&&rsi.at(-1)<=100,'Wilder RSI geçerli aralıkta olmalı');
const period=calculatePeriodSummary([{time:1,close:100},{time:2,close:80},{time:3,close:125},{time:4,close:110}]);
assert.deepEqual({last:period.last,low:period.low,high:period.high},{last:{time:4,close:110},low:{time:2,close:80},high:{time:3,close:125}},'Dönem özeti değer ve tarih noktalarını doğru seçmeli');
assert.ok(Math.abs(period.change-10)<1e-9,'Dönem değişimi doğru hesaplanmalı');
assert.ok(Math.abs(period.position-66.6666666667)<1e-9,'Güncel fiyatın dönem aralığındaki konumu doğru hesaplanmalı');
const intradayPeriod=calculatePeriodSummary([{time:1,close:100,low:95,high:105},{time:2,close:102,low:90,high:110}]);
assert.equal(intradayPeriod.low.close,90,'Dönem düşüğü gün içi düşük serisinden gelmeli');
assert.equal(intradayPeriod.high.close,110,'Dönem yükseği gün içi yüksek serisinden gelmeli');
const adjusted=resultPriceValues({indicators:{quote:[{close:[100,90]}],adjclose:[{adjclose:[50,60]}]}},{adjusted:true});
assert.deepEqual(adjusted,[50,60],'Performans hesaplaması düzeltilmiş kapanışı tercih etmeli');
const common=commonPerformanceWindow(['a','b','c'],[null,100,110],[50,60,66]);
assert.deepEqual(common.labels,['b','c'],'Portföy ve ölçüt aynı ilk ortak tarihte başlamalı');
assert.ok(Math.abs(common.portfolio[0])<1e-9&&Math.abs(common.benchmark[0])<1e-9&&Math.abs(common.portfolio[1]-10)<1e-9&&Math.abs(common.benchmark[1]-10)<1e-9,'Ortak başlangıçta her iki seri yüzde sıfıra bazlanmalı');
assert.equal(isPortfolioSummaryComplete([],new Set()),true,'Eksiksiz portföy özeti yayınlanabilmeli');
assert.equal(isPortfolioSummaryComplete(['AAPL'],new Set()),false,'Fiyatı eksik pozisyon varken toplam yayınlanmamalı');

const sandbox={module:{exports:{}},exports:{},require,URLSearchParams,URL,AbortSignal,fetch:()=>{throw new Error('testte ağ çağrısı yapılmamalı')}};
vm.runInNewContext(priceApi+'\nmodule.exports._test={numberValue,cleanQuery};',sandbox);
assert.equal(sandbox.module.exports._test.numberValue('N/A'),null,'N/A sıfır fiyat olmamalı');
assert.equal(sandbox.module.exports._test.numberValue('-'),null,'Eksik fiyat sıfır olmamalı');
assert.equal(sandbox.module.exports._test.numberValue('$1,234.56'),1234.56);
assert.match(priceApi,/TradingView anlık yedek/,'BIST ve FX için bağımsız anlık yedek sağlayıcı bulunmalı');
assert.match(priceApi,/providerChoice==='tradingview'/,'Yedek sağlayıcı bağımsız olarak doğrulanabilmeli');
assert.match(priceApi,/s-maxage=10, stale-while-revalidate=5/,'Fiyat önbelleği seçilebilir 15 saniyelik yenilemeyle uyumlu olmalı');
assert.match(priceApi,/lastKnownGood/,'Sağlayıcı kesintisi için son başarılı veri koruması bulunmalı');
const fundamentalSandbox={module:{exports:{}},exports:{},AbortSignal,fetch:()=>{throw new Error('testte ağ çağrısı yapılmamalı')}};
vm.runInNewContext(fundamentalsApi+'\nmodule.exports._test={numberValue,trailingEps};',fundamentalSandbox);
assert.equal(fundamentalSandbox.module.exports._test.numberValue('0.35%'),0.35,'Temettü yüzdesi doğru ayrıştırılmalı');
assert.equal(fundamentalSandbox.module.exports._test.numberValue('4,623,874,049,400'),4623874049400,'Piyasa değeri doğru ayrıştırılmalı');
assert.equal(fundamentalSandbox.module.exports._test.trailingEps({data:{earningsPerShare:[{type:'PreviousQuarter',earnings:1},{type:'PreviousQuarter',earnings:2},{type:'PreviousQuarter',earnings:3},{type:'PreviousQuarter',earnings:4}]}}),10,'TTM EPS son dört gerçekleşmiş çeyrekten hesaplanmalı');
assert.match(fundamentalsApi,/status:'provider_error'/,'Temel veri sağlayıcı hatası veri yok durumundan ayrılmalı');
assert.match(fundamentalsApi,/status:bist\|\|us\?'no_data':'unsupported'/,'Temel veride desteklenmeme ve gerçek veri yok durumları ayrılmalı');
const dividendSandbox={module:{exports:{}},exports:{},AbortSignal,fetch:()=>{throw new Error('testte ağ çağrısı yapılmamalı')}};
vm.runInNewContext(dividendsApi+'\nmodule.exports._test={parseDate,parseAmount};',dividendSandbox);
assert.equal(dividendSandbox.module.exports._test.parseAmount('$0.27'),0.27,'Temettü tutarı doğru ayrıştırılmalı');
assert.equal(new Date(dividendSandbox.module.exports._test.parseDate('09/15/2026')).toISOString().slice(0,10),'2026-09-15','Temettü tarihi doğru ayrıştırılmalı');
assert.match(dividendsApi,/status:'unsupported'/,'Desteklenmeyen temettü ürünleri ayrılmalı');
assert.match(dividendsApi,/status:'provider_error'/,'Temettü sağlayıcı hatası ayrı durum olmalı');
assert.match(dividendsApi,/function fetchBist[\s\S]*dividend_amount_upcoming[\s\S]*dividend_ex_date_upcoming/,'BIST yaklaşan temettüleri TradingView kaynağından alınmalı');

assert.equal((html.match(/fresh=/g)||[]).length,0,'Önbelleği bozan fresh parametresi kalmamalı');
assert.match(html,/let priceRequestId = 0;/,'Ana grafik yarış koruması bulunmalı');
assert.doesNotMatch(html,/function compareStock\s*\(/,'Ana grafik karşılaştırma işlevi kaldırılmalı');
assert.doesNotMatch(html,/let compareData\s*=/,'Ana grafik karşılaştırma durumu kaldırılmalı');
assert.doesNotMatch(html,/data-action=['"]compare['"]/,'Favorilerde karşılaştırma düğmesi kalmamalı');
assert.match(html,/className='favorite-menu-trigger'/,'Favorilerde hızlı işlem düğmesi bulunmalı');
assert.match(html,/menuAction\('Grafiği Aç'[^]*menuAction\('Fiyat Alarmı Kur'[^]*menuAction\('Portföye Ekle'[^]*menuAction\('Favorilerden Çıkar'/,'Hızlı işlem menüsü dört temel eylemi içermeli');
assert.match(html,/id="favoriteDetailDialog"[^>]*aria-labelledby="favoriteDetailTitle"/,'Favoriler için erişilebilir hızlı detay paneli bulunmalı');
assert.match(html,/open\.addEventListener\('click',\(\)=>openFavoriteDetail\(item\)\)/,'Favori kartı hızlı detay panelini açmalı');
assert.doesNotMatch(html,/closest\('\.favorite-card'\)\)openView\('chart'\)/,'Favori kartı panel açılırken arka planda Grafik sekmesine geçmemeli');
assert.doesNotMatch(html,/activeView\.focus\(/,'Sekme paneline programatik odak verilerek mavi kenar çizgisi oluşturulmamalı');
assert.doesNotMatch(html,/class="app-view[^>]*tabindex="-1"/,'Sekme kapsayıcıları Safari tarafından yeniden odaklanabilir olmamalı');
assert.match(html,/\.app-view:focus,\.app-view:focus-visible \{ outline:none !important; \}/,'Safari sekme kapsayıcısı odak çerçevesi bastırılmalı');
assert.match(html,/body\.modal-open \{ position:fixed; left:0; right:0; width:100%; \}/,'Açık panel arka plan kaydırmasını sabitlemeli');
assert.match(html,/event\.target===favoriteDetailDialog\)closeFavoriteDetail\(\)/,'Panel dışındaki karartılmış alana dokunmak hızlı detayı kapatmalı');
assert.match(html,/Günlük düşük – yüksek[\s\S]*52 hafta düşük – yüksek[\s\S]*Piyasa değeri[\s\S]*F\/K[\s\S]*Temettü verimi[\s\S]*Hacim[\s\S]*RSI \(14\)/,'Hızlı detay temel ekonomik ve teknik göstergeleri içermeli');
assert.match(html,/Number\.isFinite\(value\)\?formatter\(value\):fallback/,'Eksik detay verileri tahmin edilmeden uygun durum metniyle gösterilmeli');
assert.match(html,/\/api\/fundamentals\?symbol=/,'Hızlı detay ayrı temel veri servisiyle zenginleştirilmeli');
assert.match(html,/F\/K \(TTM\)/,'F/K değeri gerçekleşmiş son dört çeyrek bazında etiketlenmeli');
assert.match(html,/Temel veri kaynağı:/,'Temel veri kaynağı panelde açıklanmalı');
assert.match(html,/id="favoriteDetailChart"[^>]*>Grafiği Aç<[\s\S]*id="favoriteDetailAlarm"[^>]*>Alarm Kur<[\s\S]*id="favoriteDetailPortfolio"[^>]*>Portföye Ekle</,'Hızlı detay alt eylemleri bulunmalı');
assert.match(html,/role="listbox"/,'Arama önerileri listbox olmalı');
assert.match(html,/marketTimestamp:Number\(result\.meta\?\.regularMarketTime\)\|\|points\.at\(-1\)\.time/,'Favori zamanı gerçek piyasa verisinden gelmeli');
assert.match(html,/favoriteUpdated\.textContent='Son güncelleme: '/,'Favoriler başlığında yenileme zamanı gösterilmeli');
assert.doesNotMatch(html,/favoriteUpdated\.textContent='Son fiyat zamanı: '/,'Favoriler başlığında fiyat zamanı gösterilmemeli');
assert.match(html,/id="periodSummaryTitle">Dönem Özeti/,'Dönem özeti grafiğe eklenmeli');

assert.match(html,/<title>Özer Finans v5\.5<\/title>/,'Tarayıcı başlığı yeni marka ve aday sürüm adını kullanmalı');
assert.match(html,/class="page-brand"[\s\S]*assets\/ozer-finans-mark\.svg[\s\S]*Özer Finans/,'Ana ekran Özer Finans marka kilidini göstermeli');
assert.match(html,/class="desktop-brand brand-lockup"[\s\S]*assets\/ozer-finans-mark\.svg[\s\S]*Özer Finans/,'Masaüstü menüsü yeni marka kimliğini kullanmalı');
assert.equal((html.match(/class="page-brand"/g)||[]).length,4,'Özer Finans marka kilidi dört ana sayfanın tamamında bulunmalı');
assert.match(html,/\.page-brand \{[^}]*justify-content:center;/,'Sayfa marka kilidi yatay olarak ortalanmalı');
assert.match(html,/\.version-badge \{[^}]*border:0;[^}]*opacity:\.62;/,'Sürüm bilgisi rozetsiz, küçük ve silik gösterilmeli');
assert.match(logoSvg,/<rect x="1" y="1" width="62" height="62" rx="16" fill="#fff"/,'Özer Finans logosu beyaz zeminli uygulama ikonu olmalı');
assert.match(html,/\.portfolio-head \{[^}]*padding:16px;[^}]*border:1px solid var\(--line\);[^}]*border-radius:14px;/,'Portföy üst özeti tüm ekranlarda çerçeveli kart olmalı');
assert.match(html,/\.portfolio-head-value \{[^}]*font-size:1\.5rem;/,'Portföy toplam değeri hafifçe büyütülmeli');
assert.match(html,/id="portfolioCurrencyToggle"[^>]*aria-pressed="false"[^>]*>⇄<\/button>/,'Portföy üst özetinde dönüşüm düğmesi bulunmalı');
assert.match(html,/let portfolioDisplayCurrency = 'AUTO';[\s\S]*presentationFactor=summaryToUsd\/tryToUsd;/,'Portföy özeti TL dönüşümünü çapraz kurla hesaplamalı');
assert.match(html,/portfolioCurrencyToggle\.addEventListener\('click',[\s\S]*portfolioDisplayCurrency==='TRY'\?'AUTO':'TRY'[\s\S]*renderPortfolio\(\{refreshBenchmark:false,refreshDividends:false\}\)/,'Dönüşüm düğmesi yalnız fiyat özetini yeniden hesaplamalı');
assert.match(html,/portfolioSummaryCurrencyNote\.textContent=showTry\?'Portföy özeti ve dağılım değerleri TL bazında gösteriliyor\.'/,'TL görünümünde özet açıklaması seçili para birimini doğru anlatmalı');
assert.match(html,/\.market-summary-head #marketRefresh,\.favorites-panel-head #favoriteRefresh \{ min-height:38px; padding:6px 10px; font-size:\.75rem; \}/,'Özet sayfasındaki yenile düğmeleri kompakt olmalı');
assert.ok((html.match(/labels:solidLegendLabels\(colors\.text\)/g)||[]).length>=2,'Fiyat ve RSI grafiklerinin lejant örnekleri dolu renk kullanmalı');
assert.match(html,/function solidLegendLabels\(color\)[\s\S]*fillStyle:fill,strokeStyle:fill,lineWidth:0/,'Lejant renk kutularının içi seri rengiyle tamamen doldurulmalı');
assert.match(html,/\.market-summary-head h2,\.favorites-panel h2,\.chart-page > h2,\.portfolio-head h2 \{ font-size:1\.17rem; \}/,'Dört ana bölüm başlığı Portföy Özet Analizi ile aynı puntoda olmalı');
assert.match(html,/@media \(max-width:760px\) \{[\s\S]*body \{[^}]*padding:max\(4px,env\(safe-area-inset-top,0px\)\)/,'Mobil üst boşluk sabit marj yerine güvenli alan kadar olmalı');
assert.match(html,/main \{[^}]*margin:0 auto; padding:10px 6px 20px;/,'Mobil ana çerçeve üst ve yan boşlukları azaltılmalı');
assert.match(html,/\.market-summary \{ order:1; margin-bottom:14px; padding:10px;/,'Mobil piyasa özeti yan dolgusu azaltılmalı');
assert.match(html,/\.favorite-row \{[^}]*grid-template-columns:minmax\(0,1fr\) 36px;/,'Favori satırı kompakt işlem sütunu kullanmalı');
assert.match(html,/\.favorite-menu-trigger,\.favorite-remove \{[^}]*width:36px; height:36px;/,'Favori işlem düğmeleri görsel olarak kompakt olmalı');
assert.match(html,/\.favorite-menu-trigger::before,\.favorite-remove::before \{[^}]*inset:-4px;/,'Kompakt favori düğmelerinin dokunma alanı 44 piksel kalmalı');
assert.match(html,/\.market-card \{[^}]*min-height:60px; padding:7px 10px;/,'Piyasa kartları dikeyde kompakt olmalı');
assert.match(html,/\.market-card \{[^}]*grid-template-columns:minmax\(0,1fr\) auto;[^}]*grid-template-rows:auto auto;/,'Piyasa fiyatı ile yüzde değişim aynı satırda yer almalı');
assert.match(html,/\.market-card-label \{ grid-column:1\/-1; \}/,'Piyasa ürün adı fiyat satırının üzerinde kalmalı');
assert.match(html,/\.market-card strong \{[^}]*font-size:\.96rem; \}/,'Piyasa fiyat puntosu hafifçe büyütülmeli');
assert.match(html,/\.market-card small \{[^}]*font-size:\.74rem; \}/,'Piyasa değişim puntosu hafifçe büyütülmeli');
assert.match(html,/\.market-card-label \.market-card-symbol \{ display:inline;/,'Piyasa adı ve kodu gereksiz ek satır oluşturmamalı');
assert.match(html,/viewport-fit=cover/,'iOS güvenli alanı için viewport-fit=cover bulunmalı');
assert.match(html,/apple-mobile-web-app-capable/,'iOS bağımsız web uygulaması meta bilgisi bulunmalı');
assert.match(html,/\.mobile-bottom-nav \{ position:fixed !important;[^}]*bottom:0;/,'Mobil alt menü ekranın fiziksel altına sabitlenmeli');
assert.match(html,/padding:6px 6px calc\(6px \+ env\(safe-area-inset-bottom,0px\)\)/,'Güvenli alan menüyü yukarı taşımak yerine iç dolgu olarak uygulanmalı');
assert.doesNotMatch(html,/bottom:max\(8px,env\(safe-area-inset-bottom\)\)/,'Güvenli alan menünün tamamını yukarı taşımamalı');
assert.match(html,/id="pullRefreshIndicator"[^>]*role="status"/,'Üstten çekerek yenileme için erişilebilir durum göstergesi bulunmalı');
assert.match(html,/document\.addEventListener\('touchmove',[\s\S]*event\.preventDefault\(\)[\s\S]*\{passive:false\}\)/,'Üstten çekme hareketi mobil tarayıcının doğal sıçramasıyla çakışmamalı');
assert.match(html,/async function refreshActiveViewFromPull\(\)[\s\S]*mainView\.classList\.contains\('active'\)[\s\S]*chartView\.classList\.contains\('active'\)[\s\S]*portfolioView\.classList\.contains\('active'\)/,'Çekerek yenileme Özet, Grafik ve Portföy ekranlarını kendi verileriyle güncellemeli');
assert.match(html,/pullRefreshDistance>=pullRefreshThreshold[\s\S]*runPullRefresh\(\)/,'Yenileme yalnız çekme eşiği aşılıp parmak bırakıldığında başlamalı');
assert.match(html,/id="periodRangeFill"/,'Dönem içi fiyat konum barı bulunmalı');
assert.match(html,/className='favorite-market-time'/,'Her favoride fiyat zamanı alanı bulunmalı');
assert.match(html,/function favoriteLogoUrls\(symbol\)[\s\S]*financialmodelingprep\.com\/image-stock\/[\s\S]*eodhd\.com\/img\/logos\//,'Favori logoları iki bağımsız kaynağı sırayla kullanmalı');
assert.match(html,/const exchange=suffix==='IS'\?'IS':'US'/,'BIST sembolleri yedek logo kaynağında doğru borsaya çevrilmeli');
assert.match(html,/function appendSymbolLogo\(container,className,symbol\)[\s\S]*image\.addEventListener\('error',loadNext\)/,'Logo yükleme hatasında sonraki kaynak otomatik denenmeli');
assert.match(html,/image\.loading='eager'/,'Favori logoları Safari görünürlük tahminine bırakılmadan yüklenmeli');
assert.match(html,/img-src 'self' data: https:\/\/financialmodelingprep\.com https:\/\/eodhd\.com/,'İki logo kaynağı içerik güvenlik politikasında izinli olmalı');
assert.ok(html.indexOf('class="periods"')<html.indexOf('id="periodSummaryTitle"'),'Süre seçimi dönem özetinden önce gelmeli');
assert.ok(html.indexOf('id="portfolioList"')<html.indexOf('id="portfolioSymbol"'),'Portföy araması hisse listesinden sonra gelmeli');
assert.match(html,/\.benchmark-stats \{ grid-template-columns:repeat\(3,minmax\(0,1fr\)\); gap:6px; \}/,'Mobil getiri kıyası üç sütun olmalı');
assert.ok(html.indexOf('class="chart-wrap"')<html.indexOf('id="rsiWrap"')&&html.indexOf('id="rsiWrap"')<html.indexOf('class="periods"'),'RSI ana grafiğin hemen altında olmalı');
assert.match(html,/const keepExistingPortfolio=Boolean\(portfolioList\.querySelector\('\.portfolio-row'\)\)/,'Portföy yenilemesi mevcut kartları veri gelene kadar korumalı');
assert.match(html,/window\.scrollTo\(\{top:scrollBeforeCommit,behavior:'auto'\}\)/,'Portföy yenilemesi kaydırma konumunu korumalı');
assert.match(html,/portfolioAllocationChart\?updateDistributionChart\(portfolioAllocationChart/,'Varlık pasta grafiği yeniden oluşturulmadan güncellenmeli');
assert.match(html,/portfolioCurrencyChart\?updateDistributionChart\(portfolioCurrencyChart/,'Para birimi pasta grafiği yeniden oluşturulmadan güncellenmeli');
assert.match(html,/chart\.update\('none'\)/,'Pasta grafik güncellemesi animasyonsuz olmalı');
const toolbarMarkup=html.match(/<div class="toolbar">([\s\S]*?)<\/div><div id="meta"/)?.[1]||'';
assert.match(toolbarMarkup,/Gelişmiş Arama[\s\S]*Fiyat Alarmı[\s\S]*CSV İndir[\s\S]*PNG İndir/,'Grafik araç çubuğu dört temel işlemi içermeli');
assert.doesNotMatch(toolbarMarkup,/maToggle|rsiToggle/,'MA ve RSI kontrolleri üst araç çubuğunda kalmamalı');
assert.match(html,/class="chart-wrap"><button id="maToggle" class="chart-ma-toggle"[^>]*aria-pressed="false">MA50\/100\/200<\/button><canvas id="priceChart"/,'MA düğmesi ana grafiğin sol üstüne gömülmeli');
assert.match(html,/\.chart-ma-toggle \{[^}]*top:48px; left:58px;[^}]*min-height:40px;/,'MA düğmesi eksenlerden uzakta ve erişilebilir dokunma yüksekliğinde olmalı');
assert.doesNotMatch(html,/id="rsiToggle"/,'RSI açma kapama düğmesi kaldırılmalı');
assert.match(html,/\.rsi-wrap\{height:150px;display:block;margin-top:0\}/,'RSI grafiği daima görünür ve ana grafiğe bitişik olmalı');
assert.match(html,/columns\.push\(\{name:'RSI \(14\)'/,'RSI verisi dışa aktarmada daima yer almalı');
assert.match(html,/id="chartFavoritesToggle"[^>]*>Favoriler<[\s\S]*id="chartPortfolioToggle"[^>]*>Portföy</,'Grafik sayfasının altında Favoriler ve Portföy seçicileri bulunmalı');
assert.match(html,/className='chart-asset-item'[\s\S]*loadPrice\(item\.symbol\)/,'Kayıtlı hisse seçimi ana grafiği güncellemeli');
assert.match(html,/id="favoriteAddForm"[^>]*[\s\S]*id="favoriteSearch"[^>]*placeholder="Favorilere hisse ekle"/,'Özet favorilerinin altında ekleme araması bulunmalı');
assert.match(html,/function addOverviewFavorite\(item\)[\s\S]*favorites\.push\(\{symbol,name\}\)[\s\S]*refreshFavoriteQuotes\(\)/,'Özet aramasından seçilen hisse favorilere eklenip fiyatı yenilenmeli');
assert.doesNotMatch(html,/margin:48px auto 0/,'Mobil sayfanın üstünde sabit 48 piksel boşluk kalmamalı');
assert.match(html,/id="cashAddButton"[^>]*>\+ Nakit Ekle<[\s\S]*id="cashCurrency"[\s\S]*TRY · Türk Lirası[\s\S]*USD · ABD Doları[\s\S]*EUR · Euro[\s\S]*GBP · İngiliz Sterlini/,'Portföye dört para biriminde nakit ekleme akışı bulunmalı');
assert.match(html,/const cashKey = 'finans-grafigi-cash-balances'/,'Nakit bakiyeleri kalıcı olarak saklanmalı');
assert.match(html,/cashBalances\.forEach\(balance=>\{[\s\S]*totalValue\+=convertedValue[\s\S]*allocationValues\.push\(\{label:'Nakit '/,'Nakit bakiyeleri portföy toplamı ve dağılımına katılmalı');
assert.match(html,/data-benchmark-range="5d">1 Hafta<[\s\S]*data-benchmark-range="5y">5 Yıl<[\s\S]*data-benchmark-range="custom">Şu Tarihten İtibaren/,'Performans karşılaştırması grafik ekranındaki tüm süre seçeneklerini içermeli');
assert.match(html,/function benchmarkQuery\(\)[\s\S]*period1=[\s\S]*period2=/,'Özel başlangıç tarihi karşılaştırma sorgusuna dönüştürülmeli');
assert.match(html,/\/api\/dividends\?symbol=/,'Portföy yaklaşan temettü uç noktasını kullanmalı');
assert.match(dividendsApi,/exOrEffDate[\s\S]*paymentDate[\s\S]*sort\(\(a,b\)=>\(a\.exDate\|\|a\.paymentDate\)-\(b\.exDate\|\|b\.paymentDate\)\)/,'Temettü API hak kullanım ve ödeme tarihlerini yakından uzağa sıralamalı');
assert.match(html,/results\.flatMap\(item=>item\.events\)\.sort\(\(a,b\)=>a\.date-b\.date\)\.slice\(0,5\)/,'Takvim yalnız yaklaşan en yakın beş temettüyü göstermeli');
const portfolioPriceLoader=extractFunction(scripts[0],'fetchPortfolioItem');
assert.match(portfolioPriceLoader,/range=1mo&interval=1d/,'Portföy özeti için yalnız gerekli kısa fiyat geçmişi alınmalı');
assert.doesNotMatch(portfolioPriceLoader,/\/api\/dividends/,'Yavaş temettü isteği portföy fiyat özetini engellememeli');
assert.match(html,/async function renderPortfolioDividends\(positions\)/,'Temettü takvimi fiyat özetinden bağımsız yüklenmeli');
assert.match(html,/if\(refreshDividends\)renderPortfolioDividends\(valid\);[\s\S]*if\(refreshBenchmark\)renderPortfolioBenchmark\(valid\);/,'Ağır alt bölümler yalnız istendiğinde arka planda yenilenmeli');
assert.match(html,/portfolioRefreshTimerId=setInterval\(\(\)=>\{if\(!document\.hidden&&portfolioView\.classList\.contains\('active'\)\)renderPortfolio\(\{refreshBenchmark:false,refreshDividends:false\}\)\}/,'Otomatik portföy yenilemesi ağır temettü ve kıyas sorgularını tekrarlamamalı');
assert.match(html,/\.portfolio-row-head \{ display:grid; grid-template-columns:34px minmax\(0,1fr\) auto 32px;/,'Portföy kartı kompakt silme sütunu kullanmalı');
assert.match(html,/\.portfolio-delete \{[^}]*width:32px; height:32px;[^}]*font-size:\.85rem;/,'Portföy silme düğmesi görsel olarak küçük olmalı');
assert.match(html,/\.portfolio-delete::before \{[^}]*inset:-6px;/,'Küçük portföy silme düğmesinin dokunma alanı 44 piksel kalmalı');
assert.match(html,/className='portfolio-compact-line'[\s\S]*compactLine\.append\(details,profitValue\)/,'Adet, maliyet ve kâr zarar ikinci kompakt satırda bilgi kaybı olmadan gösterilmeli');
assert.match(html,/\.portfolio-row-title strong \{ font-size:1rem; \}/,'Portföy hisse kodu favorilerle aynı puntoda olmalı');
assert.match(html,/\.portfolio-row-title small \{[^}]*font-size:\.75rem; \}/,'Portföy hisse adı favorilerle aynı puntoda olmalı');
assert.match(html,/\.portfolio-current-value \{[^}]*font-size:1\.02rem;/,'Portföy güncel değeri favorilerle aynı puntoda olmalı');
assert.match(html,/\.portfolio-compact-profit \{[^}]*font-size:\.76rem;/,'Portföy kâr zarar değeri favorilerle aynı puntoda olmalı');
assert.match(html,/assetSymbol:primarySymbol\|\|currentSymbol\(\)/,'Ana grafik veri serisi sade balon için hisse kodunu taşımalı');
assert.match(html,/context\.dataset\.assetSymbol\|\|context\.dataset\.label/,'Grafik veri balonu şirketin uzun adı yerine hisse kodunu kullanmalı');
assert.match(html,/\.distribution-chart-wrap \{ position:relative; height:150px;/,'Portföy dağılım halkaları kompakt yükseklikte olmalı');
assert.match(html,/@media \(max-width:700px\)[\s\S]*\.distribution-grid \{ grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/,'İki dağılım grafiği mobilde de yan yana kalmalı');
assert.match(html,/\.distribution-summary:not\(\.expanded\) li:nth-child\(n\+4\)/,'Dağılım özetinde ilk üç kalem dışındakiler başlangıçta gizlenmeli');
assert.match(html,/toggle\.textContent=expanded\?'Daralt':'Tümünü Göster'/,'Dağılım ayrıntıları açılıp daraltılabilmeli');
assert.match(html,/renderDistributionCenter\(allocationCenter,sortedAllocations\)/,'Halka grafiğinin merkezinde en büyük pay gösterilmeli');
assert.match(html,/label\.textContent=items\[0\]\.label/,'Halka grafiğinin merkezinde en büyük paya sahip ürünün adı gösterilmeli');
assert.doesNotMatch(html,/id="themeToggle"/,'Tema düğmesi ekranın üzerinde sabit kalmamalı');
assert.match(html,/id="otherView"[\s\S]*data-theme-choice="light"[\s\S]*data-theme-choice="dark"[\s\S]*data-theme-choice="system"/,'Diğer ekranı Açık, Koyu ve Sistem tema seçeneklerini içermeli');
assert.match(html,/id="otherView"[\s\S]*id="backupDownload"[\s\S]*id="restoreBackup"/,'Veri yedekleme araçları Diğer ekranında korunmalı');
assert.match(html,/function startRefreshTimers\(\)[\s\S]*refreshInterval/,'Otomatik yenileme süresi kullanıcı tercihine göre yeniden başlatılmalı');
assert.match(html,/savedRefreshInterval===null\?15000:Number\(savedRefreshInterval\)/,'Yeni kullanıcılar için otomatik yenileme varsayılan olarak 15 saniye olmalı');
assert.match(html,/themeMedia\.addEventListener\('change'[\s\S]*themePreference==='system'/,'Sistem teması cihaz görünümü değiştiğinde otomatik uygulanmalı');
assert.match(html,/themeColorMeta\.content=resolved==='light'\?'#f8fafc':'#101827'/,'PWA üst çubuğu seçili temayla eşleşmeli');
assert.match(html,/for="favoriteSearch">Favorilere eklenecek hisseyi ara/,'Favori aramasının kalıcı erişilebilir adı olmalı');
assert.match(html,/for="portfolioSymbol">Portföye eklenecek hisseyi ara/,'Portföy aramasının kalıcı erişilebilir adı olmalı');
assert.match(html,/for="benchmarkSearch">Karşılaştırma ölçütü ara/,'Ölçüt aramasının kalıcı erişilebilir adı olmalı');
assert.match(html,/dialog\.addEventListener\('cancel',event=>\{event\.preventDefault\(\);dialog\.close\(\)\}\)/,'Tüm paneller Escape ile kapanmalı');
assert.match(html,/document\.addEventListener\('keydown',event=>\{[\s\S]*event\.key!=='Escape'[\s\S]*dialog\.close\(\)/,'Native cancel üretmeyen tarayıcılarda Escape yedeği bulunmalı');
assert.match(html,/id="backupFileName"/,'Özel Türkçe dosya seçici seçilen dosya adını göstermeli');
assert.match(html,/id="portfolioCostCurrency"[\s\S]*id="portfolioPurchaseDate"/,'Portföy maliyet para birimi ve alım tarihi kaydedilebilmeli');
assert.match(html,/historicalUsdRate\(costCurrency,position\.purchaseDate\)/,'Maliyet, alım tarihindeki kurla özet para birimine çevrilmeli');
assert.match(html,/Kısmi sonuç gösterilmedi\. Eksik veri/,'Eksik varlıkla performans kıyası sessizce yayınlanmamalı');
assert.match(html,/prepareVisibleRsi\(symbol,points\)/,'Kısa dönem RSI için görünür dönem öncesi veri kullanılmalı');
assert.match(html,/En yeni fiyat:/,'Piyasa özetinde istek zamanından ayrı gerçek fiyat zamanı gösterilmeli');
assert.match(html,/@media \(min-width:761px\) and \(max-width:900px\)/,'Tablet geçişi için ayrı düzen bulunmalı');
assert.match(html,/mobileMoreNav'\)\.addEventListener\('click',[\s\S]*openView\('other'\)/,'Mobil Diğer düğmesi sabit ayarlar ekranını açmalı');
assert.match(html,/\.settings-grid \{ display:grid; grid-template-columns:1fr;/,'Diğer ekranındaki ayar kartları yatay satırlar halinde sıralanmalı');
assert.match(html,/\.settings-horizontal \{ display:grid; grid-template-columns:minmax\(210px,\.8fr\) minmax\(320px,1\.2fr\)/,'İlk dört ayar kartının içeriği masaüstünde yatay yerleşmeli');
assert.match(html,/\.setting-switch \{[^}]*padding:0; border:0;/,'Fiyat alarmı anahtarı ikinci bir kutu içine alınmamalı');
assert.ok(html.indexOf('id="backupTitle"')<html.indexOf('id="helpTitle"'),'Yardım ve uygulama bilgileri Veri Yedekleme bölümünden sonra gelmeli');

console.log('Özer Finans v5.5 regresyon testleri başarılı.');
