const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');

const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const priceApi=fs.readFileSync(path.join(root,'api','price.js'),'utf8');
const fundamentalsApi=fs.readFileSync(path.join(root,'api','fundamentals.js'),'utf8');
const dividendsApi=fs.readFileSync(path.join(root,'api','dividends.js'),'utf8');
const dividendsBatchApi=fs.readFileSync(path.join(root,'api','dividends-batch.js'),'utf8');
const dividendHistoryApi=fs.readFileSync(path.join(root,'api','dividend-history.js'),'utf8');
const goldApi=fs.readFileSync(path.join(root,'api','gold.js'),'utf8');
const searchApi=fs.readFileSync(path.join(root,'api','search.js'),'utf8');
const logoApi=fs.readFileSync(path.join(root,'api','logo.js'),'utf8');
const tefasApi=fs.readFileSync(path.join(root,'api','tefas.js'),'utf8');
const quoteApi=fs.readFileSync(path.join(root,'api','quote.js'),'utf8');
const pricesApi=fs.readFileSync(path.join(root,'api','prices.js'),'utf8');
const accountApi=fs.readFileSync(path.join(root,'api','account.js'),'utf8');
const authConfigApi=fs.readFileSync(path.join(root,'lib','account-routes','auth-config.js'),'utf8');
const userStateApi=fs.readFileSync(path.join(root,'lib','account-routes','user-state.js'),'utf8');
const authAccount=fs.readFileSync(path.join(root,'assets','auth-account.js'),'utf8');
const authStore=fs.readFileSync(path.join(root,'lib','auth-store.js'),'utf8');
const authLoginApi=fs.readFileSync(path.join(root,'lib','account-routes','auth-login.js'),'utf8');
const authRegisterApi=fs.readFileSync(path.join(root,'lib','account-routes','auth-register.js'),'utf8');
const adminInvitesApi=fs.readFileSync(path.join(root,'lib','account-routes','admin-invites.js'),'utf8');
const authBootstrapApi=fs.readFileSync(path.join(root,'lib','account-routes','auth-bootstrap.js'),'utf8');
const storageEvents=fs.readFileSync(path.join(root,'assets','storage-events.js'),'utf8');
const brandPng=fs.readFileSync(path.join(root,'assets','brand-symbol-a.png'));
const chartVendor=fs.readFileSync(path.join(root,'assets','chart.umd.min.js'),'utf8');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));
const vercelIgnore=fs.readFileSync(path.join(root,'.vercelignore'),'utf8');

function pngDimensions(buffer){
  assert.equal(buffer.subarray(1,4).toString(),'PNG','Dosya geçerli PNG imzası taşımalı');
  return{width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20)};
}

function extractFunction(source,name){
  const start=source.indexOf('function '+name);
  assert.notEqual(start,-1,name+' bulunamadı');
  const brace=source.indexOf('{',start);
  let depth=0;
  for(let index=brace;index<source.length;index++){
    if(source[index]==='{')depth++;
    if(source[index]==='}'){
      depth--;
      if(depth===0)return source.slice(start,index+1);
    }
  }
  throw new Error(name+' kapanış parantezi bulunamadı');
}

const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(match=>match[1]).filter(Boolean);
scripts.forEach((script,index)=>assert.doesNotThrow(()=>new Function(script),'İstemci betiği '+(index+1)+' sözdizimi'));
assert.doesNotThrow(()=>new Function('module','exports','require',priceApi),'Fiyat API sözdizimi');
assert.doesNotThrow(()=>new Function('module','exports','require',quoteApi),'Güncel fiyat API sözdizimi');
assert.doesNotThrow(()=>new Function('module','exports','require',pricesApi),'Toplu fiyat API sözdizimi');
assert.doesNotThrow(()=>new Function('module','exports','require',dividendsBatchApi),'Toplu temettü API sözdizimi');
assert.doesNotThrow(()=>new Function('module','exports','require',accountApi),'Birleşik hesap API sözdizimi');
assert.doesNotThrow(()=>new Function('module','exports','require',authConfigApi),'Üyelik yapılandırma API sözdizimi');
assert.doesNotThrow(()=>new Function('module','exports','require',userStateApi),'Kullanıcı bulut verisi API sözdizimi');
assert.doesNotThrow(()=>new Function(authAccount),'Hesap oturum istemcisi sözdizimi');
assert.doesNotThrow(()=>new Function('module','exports','require',authStore),'Şifreli üyelik deposu sözdizimi');
assert.doesNotThrow(()=>new Function('module','exports','require',authLoginApi),'Giriş API sözdizimi');
assert.doesNotThrow(()=>new Function('module','exports','require',authRegisterApi),'Davetli kayıt API sözdizimi');
assert.doesNotThrow(()=>new Function('module','exports','require',adminInvitesApi),'Yönetici davet API sözdizimi');
assert.match(authBootstrapApi,/trim\(\)\.toLowerCase\(\)/,'Kurulum kodu dil bağımsız biçimde küçük/büyük harf duyarsız olmalı');
assert.doesNotThrow(()=>new Function(storageEvents),'Yerel değişiklik gözlemcisi sözdizimi');
assert.doesNotThrow(()=>new Function('module','exports','require',fundamentalsApi),'Temel veri API sözdizimi');
assert.doesNotThrow(()=>new Function('module','exports','require',dividendsApi),'Temettü API sözdizimi');
assert.doesNotThrow(()=>new Function('module','exports','require',dividendHistoryApi),'Temettü geçmişi API sözdizimi');
assert.doesNotThrow(()=>new Function('module','exports','require','URLSearchParams',goldApi),'Altın API sözdizimi');
assert.doesNotThrow(()=>new Function('module','exports','require',searchApi),'Arama API sözdizimi');
assert.doesNotThrow(()=>new Function('module','exports','require','Buffer',logoApi),'Logo API sözdizimi');

const clientFunctions=['fillMissingRates','calculateRsi','sma','calculatePeriodSummary','normalizePerformance','resultPriceValues','commonPerformanceWindow','isPortfolioSummaryComplete','portfolioConversionFactor','calculateDrip'].map(name=>extractFunction(scripts[0],name)).join('\n');
const {fillMissingRates,calculateRsi,sma,calculatePeriodSummary,resultPriceValues,commonPerformanceWindow,isPortfolioSummaryComplete,portfolioConversionFactor,calculateDrip}=new Function(clientFunctions+';return {fillMissingRates,calculateRsi,sma,calculatePeriodSummary,resultPriceValues,commonPerformanceWindow,isPortfolioSummaryComplete,portfolioConversionFactor,calculateDrip};')();
const mergePortfolioBooks=new Function(extractFunction(scripts[0],'mergePortfolioBooks')+';return mergePortfolioBooks;')();

assert.deepEqual(fillMissingRates([null,null,2,null,3,null]),[null,null,2,2,3,3],'Gelecekteki kur geçmişe taşınmamalı');
assert.deepEqual(sma([null,1,2,3],3),[null,null,null,2],'Eksik değer içeren MA penceresi hesaplanmamalı');
const rsi=calculateRsi([1,2,3,2,4,5,4,6,7,8,7,9,10,11,12,13,14,13,15,16],14);
assert.ok(Number.isFinite(rsi.at(-1))&&rsi.at(-1)>=0&&rsi.at(-1)<=100,'Wilder RSI geçerli aralıkta olmalı');
const period=calculatePeriodSummary([{time:1,close:100},{time:2,close:80},{time:3,close:125},{time:4,close:110}]);
assert.deepEqual({last:period.last,low:period.low,high:period.high},{last:{time:4,close:110},low:{time:2,close:80},high:{time:3,close:125}},'Dönem özeti değer ve tarih noktalarını doğru seçmeli');
assert.ok(Math.abs(period.change-10)<1e-9,'Dönem değişimi doğru hesaplanmalı');
assert.ok(Math.abs(period.position-66.6666666667)<1e-9,'Güncel fiyatın dönem aralığındaki konumu doğru hesaplanmalı');
const intradayPeriod=calculatePeriodSummary([{time:1,close:100,low:95,high:105},{time:2,close:102,low:90,high:110}]);
assert.equal(intradayPeriod.low.close,90,'Dönem düşüğü gün içi düşük serisinden gelmeli');
assert.equal(intradayPeriod.high.close,110,'Dönem yükseği gün içi yüksek serisinden gelmeli');
const adjusted=resultPriceValues({indicators:{quote:[{close:[100,90]}],adjclose:[{adjclose:[50,60]}]}},{adjusted:true});
assert.deepEqual(adjusted,[50,60],'Performans hesaplaması düzeltilmiş kapanışı tercih etmeli');
const common=commonPerformanceWindow(['a','b','c'],[null,100,110],[50,60,66]);
assert.deepEqual(common.labels,['b','c'],'Portföy ve ölçüt aynı ilk ortak tarihte başlamalı');
assert.ok(Math.abs(common.portfolio[0])<1e-9&&Math.abs(common.benchmark[0])<1e-9&&Math.abs(common.portfolio[1]-10)<1e-9&&Math.abs(common.benchmark[1]-10)<1e-9,'Ortak başlangıçta her iki seri yüzde sıfıra bazlanmalı');
assert.equal(isPortfolioSummaryComplete([],new Set()),true,'Eksiksiz portföy özeti yayınlanabilmeli');
assert.equal(isPortfolioSummaryComplete(['AAPL'],new Set()),false,'Fiyatı eksik pozisyon varken toplam yayınlanmamalı');
assert.ok(Math.abs(portfolioConversionFactor(0.025,1)-0.025)<1e-12,'Tek para birimli TL portföy USD karşılığına TRYUSD kuruyla dönüşmeli');
assert.ok(Math.abs(portfolioConversionFactor(1,0.025)-40)<1e-12,'USD portföy TL karşılığına ters TRYUSD kuruyla dönüşmeli');
const drip=calculateDrip(10,{prices:[{time:100,close:20},{time:200,close:25}],events:[{paymentDate:100,amount:2},{paymentDate:200,amount:1}],splits:[{date:150,numerator:2,denominator:1}],source:'fixture'},10,true);
assert.ok(Math.abs(drip.quantity-22.5848)<1e-9,'DRIP vergi, ödeme fiyatı ve bölünmeyi kronolojik uygulamalı');
assert.equal(drip.dividendCount,2,'DRIP işlenen temettü sayısını raporlamalı');
const mergedBooks=mergePortfolioBooks([{id:'a',name:'Eski',positions:[{symbol:'OLD'}],cashBalances:[]},{id:'b',name:'Korunan',positions:[],cashBalances:[]}],[{id:'a',name:'Yedek',positions:[{symbol:'AAPL',purchaseDate:'2026-01-01',dripEnabled:true}],cashBalances:[{currency:'USD',amount:10}]},{id:'c',name:'Yeni',positions:[],cashBalances:[]}]);
assert.deepEqual(mergedBooks.map(item=>item.id),['a','b','c'],'Çoklu portföy yedeği mevcut sıralamayı koruyup yeni portföyleri eklemeli');
assert.equal(mergedBooks[0].name,'Yedek','Aynı kimlikli portföy yedekteki içerikle geri yüklenmeli');
assert.equal(mergedBooks[0].positions[0].dripEnabled,true,'Temettü ayarı portföyle birlikte geri yüklenmeli');

const sandbox={module:{exports:{}},exports:{},require,URLSearchParams,URL,AbortSignal,fetch:()=>{throw new Error('testte ağ çağrısı yapılmamalı')}};
vm.runInNewContext(priceApi+'\nmodule.exports._test={numberValue,cleanQuery};',sandbox);
assert.equal(sandbox.module.exports._test.numberValue('N/A'),null,'N/A sıfır fiyat olmamalı');
assert.equal(sandbox.module.exports._test.numberValue('-'),null,'Eksik fiyat sıfır olmamalı');
assert.equal(sandbox.module.exports._test.numberValue('$1,234.56'),1234.56);
assert.match(priceApi,/TradingView anlık yedek/,'BIST ve FX için bağımsız anlık yedek sağlayıcı bulunmalı');
assert.match(priceApi,/providerChoice==='tradingview'/,'Yedek sağlayıcı bağımsız olarak doğrulanabilmeli');
assert.match(priceApi,/s-maxage=10, stale-while-revalidate=5/,'Fiyat önbelleği seçilebilir 15 saniyelik yenilemeyle uyumlu olmalı');
assert.match(priceApi,/lastKnownGood/,'Sağlayıcı kesintisi için son başarılı veri koruması bulunmalı');
assert.match(priceApi,/columns:\['name','description','close','change','currency','last_bar_update_time'\][\s\S]*timeUnknown:!hasMarketTime/,'TradingView yedeği gerçek fiyat zamanını istemeli ve yoksa bilinmiyor olarak işaretlemeli');
const fundamentalSandbox={module:{exports:{}},exports:{},AbortSignal,fetch:()=>{throw new Error('testte ağ çağrısı yapılmamalı')}};
vm.runInNewContext(fundamentalsApi+'\nmodule.exports._test={numberValue,trailingEps};',fundamentalSandbox);
assert.equal(fundamentalSandbox.module.exports._test.numberValue('0.35%'),0.35,'Temettü yüzdesi doğru ayrıştırılmalı');
assert.equal(fundamentalSandbox.module.exports._test.numberValue('4,623,874,049,400'),4623874049400,'Piyasa değeri doğru ayrıştırılmalı');
assert.equal(fundamentalSandbox.module.exports._test.trailingEps({data:{earningsPerShare:[{type:'PreviousQuarter',earnings:1},{type:'PreviousQuarter',earnings:2},{type:'PreviousQuarter',earnings:3},{type:'PreviousQuarter',earnings:4}]}}),10,'TTM EPS son dört gerçekleşmiş çeyrekten hesaplanmalı');
assert.match(fundamentalsApi,/status:'provider_error'/,'Temel veri sağlayıcı hatası veri yok durumundan ayrılmalı');
assert.match(fundamentalsApi,/status:bist\|\|us\?'no_data':'unsupported'/,'Temel veride desteklenmeme ve gerçek veri yok durumları ayrılmalı');
const dividendSandbox={module:{exports:{}},exports:{},AbortSignal,fetch:()=>{throw new Error('testte ağ çağrısı yapılmamalı')}};
vm.runInNewContext(dividendsApi+'\nmodule.exports._test={parseDate,parseAmount};',dividendSandbox);
assert.equal(dividendSandbox.module.exports._test.parseAmount('$0.27'),0.27,'Temettü tutarı doğru ayrıştırılmalı');
assert.equal(new Date(dividendSandbox.module.exports._test.parseDate('09/15/2026')).toISOString().slice(0,10),'2026-09-15','Temettü tarihi doğru ayrıştırılmalı');
assert.match(dividendsApi,/status:'unsupported'/,'Desteklenmeyen temettü ürünleri ayrılmalı');
assert.match(dividendsApi,/status:'provider_error'/,'Temettü sağlayıcı hatası ayrı durum olmalı');
assert.match(dividendsApi,/function fetchBist[\s\S]*dividend_amount_upcoming[\s\S]*dividend_ex_date_upcoming/,'BIST yaklaşan temettüleri TradingView kaynağından alınmalı');
assert.match(dividendHistoryApi,/paymentDate:parseDate\(row\.paymentDate\)\|\|parseDate\(row\.exOrEffDate\)/,'DRIP ödeme tarihi yoksa hak kullanım tarihine dönmeli');
assert.match(dividendHistoryApi,/price\.events\?\.splits/,'DRIP hesaplaması için bölünmeler servisten dönmeli');
assert.match(dividendHistoryApi,/Object\.values\(price\.events\?\.dividends\|\|\{\}\)[\s\S]*dateBasis:'ex_date_fallback'/,'Nasdaq geçmişi olmayan MINT benzeri ETF’lerde Yahoo dağıtımları yedek olmalı');
assert.match(dividendHistoryApi,/nasdaqEvents\.length\?nasdaqEvents:yahooEvents/,'Nasdaq ödeme tarihleri varsa öncelikli, yoksa Yahoo olayları kullanılmalı');
const goldSandbox={module:{exports:{}},exports:{},AbortSignal,URLSearchParams,fetch:()=>{throw new Error('testte ağ çağrısı yapılmamalı')}};
vm.runInNewContext(goldApi,goldSandbox);
const goldTest=goldSandbox.module.exports._test;
assert.ok(Math.abs(3100*40/goldTest.TROY_OUNCE_GRAMS-3986.695)<0.01,'Gram altın ons × USDTRY ÷ troy ons gramı formülüyle hesaplanmalı');
const aligned=goldTest.alignCalculated({timestamp:[1],indicators:{quote:[{close:[3100]}]}},{timestamp:[1],indicators:{quote:[{close:[40]}]}});
assert.ok(Math.abs(aligned[0].close-3100*40/goldTest.TROY_OUNCE_GRAMS)<1e-9,'Gram altın serisi ons ve kuru aynı tarihte birleştirmeli');
assert.match(goldApi,/columns:\['name','close','change','last_bar_update_time'\][\s\S]*asOf:Math\.min\(goldTime,fxTime\)/,'Gram altın zamanı ons ve kur bileşenlerinden daha eski olan gerçek güncelleme zamanını kullanmalı');
assert.match(goldApi,/if\(spot\?\.asOf\)\{payload\.chart\.result\[0\]\.meta\.regularMarketTime=spot\.asOf;payload\._finansTool\.asOf=spot\.asOf\}/,'Canlı gram altın kartı günlük mumun 07:00 zamanını göstermemeli');
assert.equal(goldTest.turkishNumber('11.253,14'),11253.14,'Fiziki altın alış fiyatı Türkçe sayı biçiminden doğru ayrıştırılmalı');
assert.match(goldApi,/Truncgil serbest piyasa alış[\s\S]*GenelPara serbest piyasa alış/,'Fiziki altın için Vercel uyumlu birincil ve yedek sağlayıcı bulunmalı');
assert.match(searchApi,/ALTIN-GRAM[\s\S]*ALTIN-CEYREK[\s\S]*ALTIN-YARIM[\s\S]*ALTIN-TAM[\s\S]*ALTIN-CUMHURIYET[\s\S]*ALTIN-ATA/,'Altın ürünleri arama kataloğunda bulunmalı');

assert.equal((html.match(/[?&]fresh=/g)||[]).length,0,'Önbelleği bozan fresh sorgu parametresi kalmamalı');
assert.match(html,/let priceRequestId = 0;/,'Ana grafik yarış koruması bulunmalı');
assert.doesNotMatch(html,/function compareStock\s*\(/,'Ana grafik karşılaştırma işlevi kaldırılmalı');
assert.doesNotMatch(html,/let compareData\s*=/,'Ana grafik karşılaştırma durumu kaldırılmalı');
assert.doesNotMatch(html,/data-action=['"]compare['"]/,'Favorilerde karşılaştırma düğmesi kalmamalı');
assert.match(html,/className='favorite-menu-trigger'/,'Favorilerde hızlı işlem düğmesi bulunmalı');
assert.match(html,/menuAction\('Grafiği Aç'[^]*menuAction\('Fiyat Alarmı Kur'[^]*menuAction\('Portföye Ekle'[^]*menuAction\('Favorilerden Çıkar'/,'Hızlı işlem menüsü dört temel eylemi içermeli');
assert.match(html,/id="favoriteDetailDialog"[^>]*aria-labelledby="favoriteDetailTitle"/,'Favoriler için erişilebilir hızlı detay paneli bulunmalı');
assert.match(html,/open\.addEventListener\('click',event=>\{if\(Date\.now\(\)<favoriteDragSuppressUntil\)/,'Favori kartı hızlı detay panelini açmalı ve sürükleme sonrası yanlışlıkla açılmamalı');
assert.match(html,/function attachFavoriteReorder\(open,row,item\)[\s\S]*setTimeout\(activate,400\)[\s\S]*persistFavoriteOrderFromDom\(\)/,'Favori kartının tamamında uzun basarak sürükleme sıralaması bulunmalı');
assert.match(html,/\.favorite-card \{[^}]*touch-action:none[^}]*user-select:none/,'Safari favori kartındaki dokunma hareketini uygulamaya bırakmalı');
assert.match(html,/pending\.scrolling\|\|distance>10[\s\S]*window\.scrollBy\(0,scrollDelta\)[\s\S]*requestAnimationFrame\(glide\)/,'Uzun basma başlamadan yapılan hareket sayfayı elle ve ivmeli kaydırmalı');
assert.match(html,/row\.replaceWith\(placeholder\)[\s\S]*document\.body\.append\(row\)/,'Sürüklemede kopya yerine gerçek favori kartı parmağı takip etmeli');
assert.match(html,/previousPositions=new Map[\s\S]*playFavoriteMotion\(candidate,[\s\S]*duration:360/,'Favoriler yer değiştirirken komşu kartlar yaylı ve yumuşak FLIP animasyonuyla yer açmalı');
assert.match(html,/pending\.ghost\.style\.transform=`translate3d[\s\S]*favorite-drag-settling[\s\S]*playFavoriteMotion\(ghost,[\s\S]*duration:320/,'Sürüklenen gerçek kart yumuşakça küçülüp hedefe oturmalı');
assert.match(html,/@keyframes favorite-card-lift[^}]*transform:scale\(1\)[\s\S]*transform:scale\(1\.04\)/,'Favori kartı sürükleme başlangıcında aniden değil animasyonla yükselmeli');
assert.match(html,/movePlaceholder\(pending\.ghostY\+pending\.ghostHeight\/2\)/,'Favori sıralama eşiği parmak noktası yerine sürüklenen kartın merkezini kullanmalı');
assert.match(html,/const followFavoriteGhost=now=>[\s\S]*requestAnimationFrame\(followFavoriteGhost\)/,'Sürüklenen favori kartı ekran yenileme hızında ara karelerle akıcı hareket etmeli');
assert.match(html,/ghostTargetX[\s\S]*ghostTargetY[\s\S]*translate3d\(\$\{pending\.ghostX-pending\.ghostLeft\}px,\$\{pending\.ghostY-pending\.ghostTop\}px,0\)/,'Sürüklenen favori kartı parmağı hem yatay hem dikey eksende takip etmeli');
assert.match(html,/open\.addEventListener\('touchstart'[\s\S]*beginInteraction\(touch\.identifier,'touch'/,'Favori kartı iPhone için ayrı TouchEvent etkileşimi başlatmalı');
assert.match(html,/window\.addEventListener\('touchmove',onTouchMove,\{passive:false\}\)[\s\S]*window\.addEventListener\('touchend',onTouchEnd,\{passive:false\}\)/,'iPhone sürüklemesi pasif olmayan touchmove ve touchend dinleyicilerine sahip olmalı');
assert.match(html,/\.favorite-row\.favorite-drag-placeholder \{ visibility:hidden; opacity:0; pointer-events:none; \}/,'Sürükleme yer tutucusundaki sağ işlem düğmeleri ikinci seçim gibi görünmemeli');
assert.match(html,/\.favorite-row\.favorite-drag-ghost \{[^}]*display:grid !important; visibility:visible !important/,'Mobil nth-child kuralı havada sürüklenen gerçek favori kartını gizlememeli');
assert.doesNotMatch(html,/\.favorite-row\.favorite-drag-ghost \.favorite-actions \{ visibility:hidden; \}/,'Havada sürüklenen kartın sağ işlem düğmeleri görünür kalmalı');
assert.match(html,/-webkit-touch-callout:none[\s\S]*document\.getSelection\(\)\?\.removeAllRanges\(\)/,'iPhone metin seçimi ve dokunma çağrı balonu sürükleme sırasında engellenmeli');
assert.match(html,/function playFavoriteMotion[\s\S]*typeof element\.animate==='function'[\s\S]*element\.style\.transition/,'Favori animasyonu eski Safari için CSS geçişi yedeğine sahip olmalı');
assert.match(html,/localStorage\.setItem\(favoritesKey, JSON\.stringify\(favorites\)\)/,'Favorilerin yeni sırası yerel depolamada kalıcı olmalı');
assert.doesNotMatch(html,/closest\('\.favorite-card'\)\)openView\('chart'\)/,'Favori kartı panel açılırken arka planda Grafik sekmesine geçmemeli');
assert.doesNotMatch(html,/activeView\.focus\(/,'Sekme paneline programatik odak verilerek mavi kenar çizgisi oluşturulmamalı');
assert.doesNotMatch(html,/class="app-view[^>]*tabindex="-1"/,'Sekme kapsayıcıları Safari tarafından yeniden odaklanabilir olmamalı');
assert.match(html,/\.app-view:focus,\.app-view:focus-visible \{ outline:none !important; \}/,'Safari sekme kapsayıcısı odak çerçevesi bastırılmalı');
assert.match(html,/body\.modal-open \{ position:fixed; left:0; right:0; width:100%; \}/,'Açık panel arka plan kaydırmasını sabitlemeli');
assert.match(html,/event\.target===favoriteDetailDialog\)closeFavoriteDetail\(\)/,'Panel dışındaki karartılmış alana dokunmak hızlı detayı kapatmalı');
assert.match(html,/Günlük düşük – yüksek[\s\S]*52 hafta düşük – yüksek[\s\S]*Piyasa değeri[\s\S]*F\/K[\s\S]*Temettü verimi[\s\S]*Hacim[\s\S]*RSI \(14\)/,'Hızlı detay temel ekonomik ve teknik göstergeleri içermeli');
assert.match(html,/Number\.isFinite\(value\)\?formatter\(value\):fallback/,'Eksik detay verileri tahmin edilmeden uygun durum metniyle gösterilmeli');
assert.match(html,/\/api\/fundamentals\?symbol=/,'Hızlı detay ayrı temel veri servisiyle zenginleştirilmeli');
assert.match(html,/F\/K \(TTM\)/,'F/K değeri gerçekleşmiş son dört çeyrek bazında etiketlenmeli');
assert.match(html,/Temel veri kaynağı:/,'Temel veri kaynağı panelde açıklanmalı');
assert.match(html,/id="favoriteDetailChart"[^>]*>Grafiği Aç<[\s\S]*id="favoriteDetailAlarm"[^>]*>Alarm Kur<[\s\S]*id="favoriteDetailPortfolio"[^>]*>Portföye Ekle</,'Hızlı detay alt eylemleri bulunmalı');
assert.match(html,/id="portfolioTargetField" hidden>Hedef portföy<select id="portfolioTargetBook"[^>]*aria-label="Hissenin ekleneceği portföy"/,'Favoriden eklemede erişilebilir hedef portföy seçicisi bulunmalı');
assert.match(html,/function openFavoritePortfolio\(item\)[\s\S]*openPortfolioDialog\(null,\{choosePortfolio:true\}\)[\s\S]*function syncPortfolioTargetChoices\(selectedId=activePortfolioId\)[\s\S]*portfolioBooks\.forEach\(book=>/,'Favori bilgi kartı mevcut portföyleri hedef seçimine yüklemeli');
assert.match(html,/const targetBook=!portfolioEditSymbol&&!portfolioTargetField\.hidden[\s\S]*const targetPositions=targetBook\.positions[\s\S]*targetPositions\.push\(\{ symbol:portfolioSelection\.symbol[\s\S]*savePortfolioBooks\(\)/,'Yeni pozisyon yalnız seçilen hedef portföye kaydedilmeli');
assert.match(html,/role="listbox"/,'Arama önerileri listbox olmalı');
assert.match(html,/marketTimestamp:Number\(result\.meta\?\.regularMarketTime\)\|\|points\.at\(-1\)\.time/,'Favori zamanı gerçek piyasa verisinden gelmeli');
assert.match(html,/favoriteUpdated\.textContent='Son güncelleme: '/,'Favoriler başlığında yenileme zamanı gösterilmeli');
assert.doesNotMatch(html,/favoriteUpdated\.textContent='Son fiyat zamanı: '/,'Favoriler başlığında fiyat zamanı gösterilmemeli');
assert.match(html,/id="periodSummaryTitle">Dönem Özeti/,'Dönem özeti grafiğe eklenmeli');

assert.match(html,/<title>Özer Finans v7\.5 Önizleme<\/title>/,'Tarayıcı başlığı önizleme sürüm adını kullanmalı');
assert.match(html,/class="page-brand"[\s\S]*assets\/brand-symbol-a\.png\?v=7\.5[\s\S]*Özer Finans/,'Ana ekran Özer Finans marka kilidini göstermeli');
assert.match(html,/class="desktop-brand brand-lockup"[\s\S]*assets\/brand-symbol-a\.png\?v=7\.5[\s\S]*Özer Finans/,'Masaüstü menüsü yeni marka kimliğini kullanmalı');
assert.equal((html.match(/class="page-brand"/g)||[]).length,4,'Özer Finans marka kilidi dört ana sayfanın tamamında bulunmalı');
assert.match(html,/\.page-brand \{[^}]*justify-content:center;/,'Sayfa marka kilidi yatay olarak ortalanmalı');
assert.match(html,/\.version-badge \{[^}]*border:0;[^}]*opacity:\.62;/,'Sürüm bilgisi rozetsiz, küçük ve silik gösterilmeli');
assert.deepEqual(pngDimensions(brandPng),{width:256,height:256},'Özer Finans A sembolü 256×256 yerel PNG olmalı');
assert.ok(fs.statSync(path.join(root,'assets','gold-mark-d.png')).size>100000,'Seçilen D altın çizimi yüksek çözünürlüklü yerel görsel olarak saklanmalı');
assert.match(html,/safe\.startsWith\('ALTIN-'\)\)return\['assets\/gold-mark-d\.png'\]/,'Bütün altın ürünleri seçilen D simgesini kullanmalı');
assert.match(html,/safe\.startsWith\('TEFAS-'\)\)return uniqueBy\(\[managerLogoUrl\(name\),managerBadgeDataUri\(name\)\]/,'TEFAS fonları önce gerçek kurum simgesini, yalnız hata halinde harf yedeğini kullanmalı');
assert.match(html,/function fundManagerIdentity\(name\)[\s\S]*AK PORTFOY[\s\S]*YAPI KREDI PORTFOY[\s\S]*QNB PORTFOY/,'Başlıca fon yönetim şirketleri adından tanınmalı');
assert.match(html,/function managerLogoUrl\(name\)[\s\S]*return manager\.asset\|\|''/,'Fon yönetim şirketi logosu ağdan değil yerel varlıktan çözülmeli');
for(const file of ['ak.png','yapi-kredi.png','is.png','qnb.png','garanti.png','ziraat.png','vakif.png','halk.png','deniz.png','teb.png','fiba.png'])assert.ok(fs.statSync(path.join(root,'assets','fund-managers',file)).size>700,'Fon yönetim şirketi logosu yerelde bulunmalı: '+file);
assert.match(html,/fund-manager-logo \{[^}]*object-fit:contain !important;[^}]*background:#fff !important;/,'Fon logoları yuvarlak kart içinde kırpılmadan görünmeli');
assert.match(html,/function positionSuggestionList\(input,list\)[\s\S]*visualViewport[\s\S]*spaceBelow<Math\.min\(190,spaceAbove\)[\s\S]*classList\.toggle\('open-up',openUp\)/,'Arama önerileri klavye ve alt menü alanına göre yukarı veya aşağı açılmalı');
assert.match(html,/\.search-suggestions\.open-up\{top:auto;bottom:calc\(100% \+ 5px\)/,'Yukarı açılan öneri listesi arama kutusunun üzerinde konumlanmalı');
assert.match(html,/\.portfolio-head \{[^}]*padding:16px;[^}]*border:1px solid var\(--line\);[^}]*border-radius:14px;/,'Portföy üst özeti tüm ekranlarda çerçeveli kart olmalı');
assert.match(html,/\.portfolio-head-value \{[^}]*font-size:1\.5rem;/,'Portföy toplam değeri hafifçe büyütülmeli');
assert.match(html,/id="portfolioCurrencyToggle"[^>]*aria-pressed="false"[^>]*>⇄<\/button>/,'Portföy üst özetinde dönüşüm düğmesi bulunmalı');
assert.match(html,/id="portfolioSummaryCard"[^>]*>[\s\S]*id="portfolioHeading">Portföyüm<[\s\S]*id="portfolioAnalysisToggle"[^>]*aria-expanded="false"[^>]*aria-controls="portfolioAnalysisSection"[\s\S]*id="portfolioAnalysisSection"[^>]*>[\s\S]*Portföy Özet Analizi[\s\S]*id="portfolioSummaryCurrencyNote"[\s\S]*id="portfolioSummary"/,'Portföy Özet Analizi içeriği korunarak aktif portföy özet kartına bağlanmalı');
assert.match(html,/\.portfolio-page \.portfolio-summary-card:not\(\.is-open\) > \.portfolio-analysis \{ display:none !important; \}[\s\S]*portfolioAnalysisToggle\.addEventListener\('click',[\s\S]*classList\.toggle\('is-open',open\)[\s\S]*setAttribute\('aria-expanded',String\(open\)\)/,'Özet analizi ok düğmesiyle erişilebilir biçimde aşağı açılıp kapanmalı');
assert.match(html,/\.portfolio-analysis-toggle \{[^}]*width:100%;[^}]*min-height:25px;[\s\S]*m8 6 4 4 4-4M8 12l4 4 4-4/,'Analiz açma kontrolü kutunun altında ince, uzun ve çift aşağı şevronlu bar olmalı');
assert.match(html,/addAnalysisRow\(table,'Toplam maliyet',[\s\S]*addAnalysisRow\(table,'Güncel toplam değer',[\s\S]*addAnalysisRow\(table,'Toplam net kâr \/ zarar',[\s\S]*addAnalysisRow\(table,'Toplam kâr \/ zarar \(%\)',[\s\S]*addAnalysisRow\(table,'Hafta başından net kâr \/ zarar',[\s\S]*addAnalysisRow\(table,'Hafta başından kâr \/ zarar \(%\)'/,'Portföy analizi moddan bağımsız toplam ve hafta başı kâr-zarar satırlarını daima göstermeli');
assert.match(html,/id="portfolioTodayMode"[^>]*>Bugün<\/button>[\s\S]*id="portfolioTotalMode"[^>]*>Toplam<\/button>[\s\S]*id="portfolioPrivacyToggle"/,'Portföy sayfasında Bugün, Toplam ve gizlilik kontrolleri bulunmalı');
assert.match(html,/id="allPortfolioHead"[^>]*>[\s\S]*class="portfolio-view-toolbar"[\s\S]*id="portfolioTodayMode"[\s\S]*id="portfolioTotalMode"[\s\S]*id="portfolioPrivacyToggle"[\s\S]*id="allPortfolioTotalValue"/,'Üç yeni kontrol Toplam Portföy kartının sağ üstünde bulunmalı');
assert.match(html,/\.portfolio-view-toolbar \{ display:flex;[^}]*gap:4px;[\s\S]*\.portfolio-metric-mode button \{ min-height:27px;[\s\S]*\.portfolio-overall-heading,\.portfolio-overall-body \{ display:flex; align-items:center; justify-content:space-between;[\s\S]*content:"\*\*\*\*\*"/,'Küçük gizlilik kontrolleri başlık hizasında sağda olmalı ve değerler beş yıldızla maskelenmeli');
assert.match(html,/function setPortfolioMetricsMode\(mode\)[\s\S]*localStorage\.setItem\(portfolioMetricsModeKey,portfolioMetricsMode\)[\s\S]*renderPortfolio\(\)/,'Bugün ve Toplam seçimi kalıcı olup portföyü yeniden hesaplamalı');
assert.match(html,/function syncPortfolioViewControls\(\)[\s\S]*portfolioView\.classList\.toggle\('is-private',portfolioPrivacyEnabled\)[\s\S]*portfolioPrivacyToggle\.addEventListener\('click',[\s\S]*localStorage\.setItem\(portfolioPrivacyKey,String\(portfolioPrivacyEnabled\)\)/,'Gizlilik düğmesi portföy rakamlarını kalıcı olarak maskelemeli');
assert.match(html,/portfolioMetricsMode==='today'\?dailyProfit:netProfit\*presentationFactor[\s\S]*selectedLabel=portfolioMetricsMode==='today'\?'Bugün ':'Toplam '/,'Aktif portföy özeti seçime göre günlük veya toplam kâr zararı göstermeli');
assert.match(html,/totalCostUsd[\s\S]*totalProfitUsd=totalUsd-totalCostUsd[\s\S]*portfolioMetricsMode==='today'\?displayedDaily:totalProfitUsd\*factor/,'Toplam Portföy özeti seçime göre günlük veya maliyet bazlı toplam kâr zararı göstermeli');
assert.match(html,/Toplam Portföy[\s\S]*id="allPortfolioTotalValue"[\s\S]*id="allPortfolioDailyChange"[\s\S]*id="allPortfolioCurrencyToggle"/,'Aktif portföy menüsünün üstünde bütün portföylerin birleşik özet kartı bulunmalı');
assert.match(html,/id="portfolioBookSelect"[\s\S]*id="portfolioBookAdd"[\s\S]*id="portfolioBookRename"[\s\S]*id="portfolioBookDelete"/,'Portföy seçme, oluşturma, yeniden adlandırma ve silme kontrolleri bulunmalı');
assert.match(html,/id="portfolioBookTabs"[^>]*aria-label="Portföy kısayolları"/,'Seçim menüsünün altında tıklanabilir portföy kısayolları bulunmalı');
assert.match(html,/portfolioBookTabs\.replaceChildren\(\)[\s\S]*className='portfolio-book-tab'[\s\S]*switchPortfolio\(book\.id\)/,'Portföy kısayolları aktif portföyü doğrudan değiştirmeli');
assert.match(html,/const portfolioBooksKey = 'finans-grafigi-portfolios-v2'/,'Çoklu portföyler ayrı ve kalıcı bir veri modelinde saklanmalı');
assert.match(html,/if\(!portfolioBooks\.length\)portfolioBooks=\[\{id:'portfolio-main',name:'Portföyüm',displayCurrency:baseCurrencyPreference,positions:legacyPortfolio,cashBalances:legacyCashBalances/,'Eski tek portföy ve nakit verisi kayıpsız varsayılan portföye taşınmalı');
assert.match(html,/function switchPortfolio\(bookId\)[\s\S]*bindActivePortfolio\(\)[\s\S]*renderChartAssetPanels\(\)[\s\S]*renderPortfolio\(\)/,'Portföy değişiminde aktif veriler, grafik seçici ve özet birlikte yenilenmeli');
assert.match(html,/portfolioBooks\.length===1[\s\S]*En az bir portföy bulunmalıdır/,'Son portföy yanlışlıkla silinememeli');
assert.match(html,/portfolioBookAdd\.disabled=portfolioBooks\.length>=50[\s\S]*En fazla 50 portföy oluşturulabilir/,'Yerel veri ve seçici kullanılabilirliği için portföy sayısı 50 ile sınırlandırılmalı');
assert.match(html,/function portfolioPresentationTarget\(summaryCurrency\)[\s\S]*summaryCurrency==='TRY'\?'USD':'TRY'/,'Aktif portföy dönüşüm hedefi TL portföyde USD, diğerlerinde TL olmalı');
assert.match(html,/portfolioConversionFactor\(summaryToUsd,targetToUsd\)/,'Portföy özeti bütün para birimi yönlerinde çapraz kurla hesaplanmalı');
assert.match(html,/portfolioCurrencyToggle\.addEventListener\('click',[\s\S]*visibleCurrency==='TRY'\?'USD':'TRY'[\s\S]*activePortfolioBook\(\)\.displayCurrency=portfolioDisplayCurrency;savePortfolioBooks\(\)[\s\S]*renderPortfolio\(\{refreshBenchmark:false,refreshDividends:false\}\)/,'Aktif portföy dönüşüm düğmesi yalnız o portföyün para birimini değiştirmeli');
assert.match(html,/allPortfolioCurrencyToggle\.addEventListener\('click',[\s\S]*localStorage\.setItem\(allPortfolioCurrencyKey,allPortfolioDisplayCurrency\);renderAllPortfoliosSummary\(\)/,'Toplam Portföy dönüşüm düğmesi yalnız birleşik toplam alanını değiştirmeli');
assert.match(html,/async function renderAllPortfoliosSummary\(priceWarmup=null\)[\s\S]*portfolioBooks\.flatMap\(book=>book\.positions\)[\s\S]*totalUsd[\s\S]*allPortfolioTotalValue\.textContent/,'Toplam Portföy kartı bütün portföyleri USD bazında birleştirmeli');
assert.match(html,/portfolioSummaryCurrencyNote\.textContent=nativeMode\?[\s\S]*'Portföydeki bütün değerler TL bazında gösteriliyor\.'[\s\S]*'Portföydeki bütün değerler USD bazında gösteriliyor\.'/,'Özet açıklaması ürünün kendi para birimi, TL veya USD tercihini doğru anlatmalı');
assert.match(html,/\.market-summary-head #marketRefresh,\.favorites-panel-head #favoriteRefresh \{ min-height:38px; padding:6px 10px; font-size:\.75rem; \}/,'Özet sayfasındaki yenile düğmeleri kompakt olmalı');
assert.ok((html.match(/labels:solidLegendLabels\(colors\.text\)/g)||[]).length>=2,'Fiyat ve RSI grafiklerinin lejant örnekleri dolu renk kullanmalı');
assert.match(html,/function solidLegendLabels\(color\)[\s\S]*fillStyle:fill,strokeStyle:fill,lineWidth:0/,'Lejant renk kutularının içi seri rengiyle tamamen doldurulmalı');
assert.match(html,/\.market-summary-head h2,\.favorites-panel h2,\.chart-page > h2,\.portfolio-head h2 \{ font-size:1\.17rem; \}/,'Dört ana bölüm başlığı Portföy Özet Analizi ile aynı puntoda olmalı');
assert.match(html,/@media \(max-width:760px\) \{[\s\S]*body \{[^}]*padding:max\(4px,env\(safe-area-inset-top,0px\)\)/,'Mobil üst boşluk sabit marj yerine güvenli alan kadar olmalı');
assert.match(html,/main \{[^}]*margin:0 auto; padding:10px 6px 20px;/,'Mobil ana çerçeve üst ve yan boşlukları azaltılmalı');
assert.match(html,/\.market-summary \{ order:1; margin-bottom:14px; padding:10px;/,'Mobil piyasa özeti yan dolgusu azaltılmalı');
assert.match(html,/\.favorite-row \{[^}]*grid-template-columns:minmax\(0,1fr\) 36px;/,'Favori satırı kompakt işlem sütunu kullanmalı');
assert.match(html,/\.favorite-menu-trigger,\.favorite-remove \{[^}]*width:36px; height:36px;/,'Favori işlem düğmeleri görsel olarak kompakt olmalı');
assert.match(html,/\.favorite-menu-trigger::before,\.favorite-remove::before \{[^}]*inset:-4px;/,'Kompakt favori düğmelerinin dokunma alanı 44 piksel kalmalı');
assert.match(html,/\.market-card \{[^}]*min-height:60px; padding:7px 10px;/,'Piyasa kartları dikeyde kompakt olmalı');
assert.match(html,/\.market-card \{[^}]*grid-template-columns:minmax\(0,1fr\) auto;[^}]*grid-template-rows:auto auto;/,'Piyasa fiyatı ile yüzde değişim aynı satırda yer almalı');
assert.match(html,/\.market-card-label \{ grid-column:1\/-1; \}/,'Piyasa ürün adı fiyat satırının üzerinde kalmalı');
assert.match(html,/\.market-card strong \{[^}]*font-size:\.96rem; \}/,'Piyasa fiyat puntosu hafifçe büyütülmeli');
assert.match(html,/\.market-card small \{[^}]*font-size:\.74rem; \}/,'Piyasa değişim puntosu hafifçe büyütülmeli');
assert.match(html,/\.market-card-label \.market-card-symbol \{ display:inline;/,'Piyasa adı ve kodu gereksiz ek satır oluşturmamalı');
assert.match(html,/viewport-fit=cover/,'iOS güvenli alanı için viewport-fit=cover bulunmalı');
assert.match(html,/apple-mobile-web-app-capable/,'iOS bağımsız web uygulaması meta bilgisi bulunmalı');
assert.match(html,/\.mobile-bottom-nav \{ position:fixed !important;[^}]*bottom:0;/,'Mobil alt menü ekranın fiziksel altına sabitlenmeli');
assert.match(html,/padding:6px 6px calc\(6px \+ env\(safe-area-inset-bottom,0px\)\)/,'Güvenli alan menüyü yukarı taşımak yerine iç dolgu olarak uygulanmalı');
assert.doesNotMatch(html,/bottom:max\(8px,env\(safe-area-inset-bottom\)\)/,'Güvenli alan menünün tamamını yukarı taşımamalı');
assert.match(html,/id="pullRefreshIndicator"[^>]*role="status"/,'Üstten çekerek yenileme için erişilebilir durum göstergesi bulunmalı');
assert.match(html,/document\.addEventListener\('touchmove',[\s\S]*event\.preventDefault\(\)[\s\S]*\{passive:false\}\)/,'Üstten çekme hareketi mobil tarayıcının doğal sıçramasıyla çakışmamalı');
assert.match(html,/async function refreshActiveViewFromPull\(\)[\s\S]*apiCache\.clear\(\)[\s\S]*runActiveRefresh\(\{force:true,leaderRequired:false\}\)/,'Çekerek yenileme önbelleği atlayıp yalnız etkin ekranı zorunlu yenilemeli');
assert.match(html,/pullRefreshDistance>=pullRefreshThreshold[\s\S]*runPullRefresh\(\)/,'Yenileme yalnız çekme eşiği aşılıp parmak bırakıldığında başlamalı');
assert.match(html,/id="periodRangeFill"/,'Dönem içi fiyat konum barı bulunmalı');
assert.match(html,/className='favorite-market-time'/,'Her favoride fiyat zamanı alanı bulunmalı');
assert.match(html,/function favoriteLogoUrls\(symbol,name\)[\s\S]*financialmodelingprep\.com\/image-stock\/[\s\S]*eodhd\.com\/img\/logos\//,'Favori logoları iki bağımsız kaynağı sırayla kullanmalı');
assert.match(html,/suffix==='IS'\?'\/api\/logo\?symbol='/,'BIST logoları için aynı kaynaklı üçüncü yedek bulunmalı');
assert.match(html,/const exchange=suffix==='IS'\?'IS':'US'/,'BIST sembolleri yedek logo kaynağında doğru borsaya çevrilmeli');
assert.match(html,/function appendSymbolLogo\(container,className,symbol,name\)[\s\S]*image\.addEventListener\('error',loadNext\)/,'Logo yükleme hatasında sonraki kaynak otomatik denenmeli');
assert.match(html,/image\.loading='eager'/,'Favori logoları Safari görünürlük tahminine bırakılmadan yüklenmeli');
assert.match(logoApi,/scanner\.tradingview\.com\/turkey\/scan[\s\S]*columns:\['name','description','logoid'\]/,'BIST logo yedeği TradingView logo kimliğini kullanmalı');
assert.match(logoApi,/s3-symbol-logo\.tradingview\.com\/[\s\S]*--big\.svg/,'Doğrulanan TradingView logosu sunucu üzerinden aktarılmalı');
assert.match(logoApi,/\^\[A-Z0-9\]\{1,12\}\\\.IS\$/,'Logo uç noktası yalnız doğrulanmış BIST sembollerini kabul etmeli');
assert.match(html,/img-src 'self' data: https:\/\/financialmodelingprep\.com https:\/\/eodhd\.com/,'İki logo kaynağı içerik güvenlik politikasında izinli olmalı');
assert.ok(html.indexOf('class="periods"')<html.indexOf('id="periodSummaryTitle"'),'Süre seçimi dönem özetinden önce gelmeli');
assert.ok(html.indexOf('id="portfolioList"')<html.indexOf('id="portfolioSymbol"'),'Portföy araması hisse listesinden sonra gelmeli');
assert.match(html,/\.benchmark-stats \{ grid-template-columns:repeat\(3,minmax\(0,1fr\)\); gap:6px; \}/,'Mobil getiri kıyası üç sütun olmalı');
assert.ok(html.indexOf('class="chart-wrap"')<html.indexOf('id="rsiWrap"')&&html.indexOf('id="rsiWrap"')<html.indexOf('class="periods"'),'RSI ana grafiğin hemen altında olmalı');
assert.match(html,/const keepExistingPortfolio=Boolean\(portfolioList\.querySelector\('\.portfolio-row'\)\)/,'Portföy yenilemesi mevcut kartları veri gelene kadar korumalı');
assert.match(html,/window\.scrollTo\(\{top:scrollBeforeCommit,behavior:'auto'\}\)/,'Portföy yenilemesi kaydırma konumunu korumalı');
assert.match(html,/portfolioAllocationChart\?updateDistributionChart\(portfolioAllocationChart/,'Varlık pasta grafiği yeniden oluşturulmadan güncellenmeli');
assert.match(html,/portfolioCurrencyChart\?updateDistributionChart\(portfolioCurrencyChart/,'Para birimi pasta grafiği yeniden oluşturulmadan güncellenmeli');
assert.match(html,/chart\.update\('none'\)/,'Pasta grafik güncellemesi animasyonsuz olmalı');
const toolbarMarkup=html.match(/<div class="toolbar">([\s\S]*?)<\/div><div id="meta"/)?.[1]||'';
assert.match(toolbarMarkup,/Gelişmiş Arama[\s\S]*Fiyat Alarmı[\s\S]*CSV İndir[\s\S]*PNG İndir/,'Grafik araç çubuğu dört temel işlemi içermeli');
assert.doesNotMatch(toolbarMarkup,/maToggle|rsiToggle/,'MA ve RSI kontrolleri üst araç çubuğunda kalmamalı');
assert.match(html,/class="chart-wrap"><button id="maToggle" class="chart-ma-toggle"[^>]*aria-pressed="false">MA50\/100\/200<\/button><canvas id="priceChart"/,'MA düğmesi ana grafiğin sol üstüne gömülmeli');
assert.match(html,/\.chart-ma-toggle \{[^}]*top:48px; left:58px;[^}]*min-height:40px;/,'MA düğmesi eksenlerden uzakta ve erişilebilir dokunma yüksekliğinde olmalı');
assert.doesNotMatch(html,/id="rsiToggle"/,'RSI açma kapama düğmesi kaldırılmalı');
assert.match(html,/\.rsi-wrap\{height:150px;display:block;margin-top:0\}/,'RSI grafiği daima görünür ve ana grafiğe bitişik olmalı');
assert.match(html,/columns\.push\(\{name:'RSI \(14\)'/,'RSI verisi dışa aktarmada daima yer almalı');
assert.match(html,/id="chartFavoritesToggle"[^>]*>Favoriler<[\s\S]*id="chartPortfolioToggle"[^>]*>Portföy</,'Grafik sayfasının altında Favoriler ve Portföy seçicileri bulunmalı');
assert.match(html,/className='chart-asset-item'[\s\S]*loadPrice\(item\.symbol\)/,'Kayıtlı hisse seçimi ana grafiği güncellemeli');
assert.match(html,/id="favoriteAddForm"[^>]*[\s\S]*id="favoriteSearch"[^>]*placeholder="Favorilere hisse ekle"/,'Özet favorilerinin altında ekleme araması bulunmalı');
assert.match(html,/function addOverviewFavorite\(item\)[\s\S]*favorites\.push\(\{symbol,name\}\)[\s\S]*refreshFavoriteQuotes\(\)/,'Özet aramasından seçilen hisse favorilere eklenip fiyatı yenilenmeli');
assert.doesNotMatch(html,/margin:48px auto 0/,'Mobil sayfanın üstünde sabit 48 piksel boşluk kalmamalı');
assert.match(html,/id="cashAddButton"[^>]*>\+ Nakit Ekle<[\s\S]*id="cashCurrency"[\s\S]*TRY · Türk Lirası[\s\S]*USD · ABD Doları[\s\S]*EUR · Euro[\s\S]*GBP · İngiliz Sterlini/,'Portföye dört para biriminde nakit ekleme akışı bulunmalı');
assert.match(html,/const cashKey = 'finans-grafigi-cash-balances'/,'Nakit bakiyeleri kalıcı olarak saklanmalı');
assert.match(html,/cashBalances\.forEach\(balance=>\{[\s\S]*totalValue\+=convertedValue[\s\S]*allocationValues\.push\(\{label:'Nakit '/,'Nakit bakiyeleri portföy toplamı ve dağılımına katılmalı');
assert.match(html,/function openCashDialog\(balance=null\)[\s\S]*Nakit Bakiyeyi Düzenle[\s\S]*cashAmount\.value=balance\?\.amount/,'Nakit kartına tıklanınca mevcut bakiye düzenleme formuna yüklenmeli');
assert.match(html,/item\.addEventListener\('click',edit\)[\s\S]*cashEditCurrency[\s\S]*edited\.currency=currency;edited\.amount=amount/,'Nakit kartı tıklama ve düzenleme akışı bulunmalı');
assert.match(html,/\.portfolio-cash-delete \{ width:24px; height:24px; min-height:24px;/,'Nakit silme düğmesi kart sınırlarında kompakt kalmalı');
assert.match(html,/data-benchmark-range="5d">1 Hafta<[\s\S]*data-benchmark-range="5y">5 Yıl<[\s\S]*data-benchmark-range="custom">Şu Tarihten İtibaren/,'Performans karşılaştırması grafik ekranındaki tüm süre seçeneklerini içermeli');
assert.match(html,/function benchmarkQuery\(\)[\s\S]*period1=[\s\S]*period2=/,'Özel başlangıç tarihi karşılaştırma sorgusuna dönüştürülmeli');
assert.match(html,/\/api\/dividends\?symbol=/,'Portföy yaklaşan temettü uç noktasını kullanmalı');
assert.match(dividendsApi,/exOrEffDate[\s\S]*paymentDate[\s\S]*events=unique\.filter[\s\S]*paymentDate\|\|item\.exDate[\s\S]*pastEvents=unique\.filter/,'Temettü API ödeme tarihine göre yaklaşan ve geçmiş olayları ayırmalı');
assert.match(html,/const upcomingDividends=results\.flatMap\(item=>item\.events\)\.sort\(\(a,b\)=>a\.date-b\.date\)[\s\S]*upcomingDividends\.length>=5[\s\S]*const pastDividends=results\.flatMap\(item=>item\.pastEvents\|\|\[\]\)\.sort\(\(a,b\)=>b\.date-a\.date\)[\s\S]*dividends=\[\.\.\.upcomingDividends,\.\.\.pastDividends\]\.slice\(0,5\)/,'Takvim hafif batch yanıtındaki geçmiş olaylarla beş satıra tamamlanmalı');
assert.doesNotMatch(html,/historyQuery='range=5y&interval=1d&events=div'/,'Temettü takvimi beş satır için beş yıllık OHLC indirmemeli');
assert.match(html,/amountText:\(Number\.isFinite\(factor\)\?dividendMoney\(item\.amount\*factor,shownCurrency\)[\s\S]*pricePrecisionNumber\(item\.quantity\)\+' adet'/,'Temettü tutarı ve adet değeri seçili hassasiyetle hazırlanmalı');
assert.match(html,/const calendarDate=Number\.isFinite\(paymentDate\)\?paymentDate:exDate;[\s\S]*date:calendarDate/,'Temettü satırının sol tarihi ödeme tarihini, yoksa hak kullanım tarihini kullanmalı');
assert.match(html,/symbol:displaySymbol\(item\.symbol\)/,'Temettü takvim verisi yalnız ürün sembolünü taşımalı');
assert.match(html,/function appendPortfolioDividendRow\(item\)[\s\S]*symbol\.textContent=item\.symbol/,'Temettü satırında sembol yanında ödeme tarihi tekrarlanmamalı');
assert.match(html,/amountText:\(Number\.isFinite\(factor\)\?dividendMoney\(item\.amount\*factor,shownCurrency\)/,'Temettü para tutarı temettüye özel para biçimleyicisini kullanmalı');
assert.match(html,/function dividendMoney\(value, currency\) \{[\s\S]*preference==='auto'\?2:Number\(preference\)[\s\S]*minimumFractionDigits:digits,maximumFractionDigits:digits/,'Temettü tutarı otomatik modda standart iki basamak kullanmalı, açık basamak tercihini korumalı');
assert.match(html,/function activePriceDecimalsPreference\(\)[\s\S]*priceDecimalsSelect\?\.value[\s\S]*function money\(value, currency\)[\s\S]*const preference=activePriceDecimalsPreference\(\)/,'Para biçimleme ekranda seçili fiyat hassasiyetini doğrudan kullanmalı');
assert.match(html,/\.dividend-row strong \{ text-align:right; white-space:nowrap;/,'Temettü tutarı tek satırda kalmalı');
assert.match(html,/@media \(max-width:760px\)[\s\S]*\.dividend-row \{ grid-template-columns:94px minmax\(42px,1fr\) auto;/,'Temettü takvimi mobilde geniş tarih sütunu ile sembol ve tutar için üç sütunu korumalı');
assert.match(html,/input \{[^}]*text-transform:none;/,'Giriş ve arama alanları kullanıcının küçük-büyük harf biçimini korumalı');
assert.doesNotMatch(html,/input \{[^}]*text-transform:uppercase/,'Giriş alanlarına genel büyük harf dönüşümü uygulanmamalı');
assert.match(html,/function foldSearchText\(value\)[\s\S]*\.toUpperCase\(\)/,'Arama görünümü harf biçimini korurken eşleşme büyük-küçük harf duyarsız kalmalı');
const portfolioPriceLoader=extractFunction(scripts[0],'fetchPortfolioMarket');
assert.match(portfolioPriceLoader,/range=1mo&interval=1d/,'Portföy özeti için yalnız gerekli kısa fiyat geçmişi alınmalı');
assert.doesNotMatch(portfolioPriceLoader,/\/api\/dividends/,'Yavaş temettü isteği portföy fiyat özetini engellememeli');
assert.match(html,/async function renderPortfolioDividends\(positions\)/,'Temettü takvimi fiyat özetinden bağımsız yüklenmeli');
assert.match(html,/if\(refreshDividends\)renderPortfolioDividends\(valid\);[\s\S]*if\(refreshBenchmark\)renderPortfolioBenchmark\(valid\);/,'Ağır alt bölümler yalnız istendiğinde arka planda yenilenmeli');
assert.match(html,/fetchPortfolioDividendsBatch\(positions\)[\s\S]*\/api\/dividends-batch\?symbols=/,'Portföy temettüleri tek toplu istemci çağrısıyla alınmalı');
assert.match(dividendsBatchApi,/MAX_SYMBOLS=40[\s\S]*mapWithLimit\(symbols,5[\s\S]*results:Object\.fromEntries/,'Toplu temettü servisi kırk sembolü kontrollü eşzamanlılıkla birleştirmeli');
assert.match(html,/portfolioDividendSnapshotsKey[\s\S]*renderCachedPortfolioDividendSnapshot\(\)[\s\S]*Son takvim kaydı gösteriliyor; güncel veriler arka planda alınıyor/,'Son başarılı temettü takvimi cihazdan anında gösterilmeli');
assert.match(html,/if\(portfolioView\.classList\.contains\('active'\)\)return renderPortfolio\(\{refreshBenchmark:false,refreshDividends:false,refreshAll:false\}\)/,'Otomatik portföy yenilemesi ağır temettü, kıyas ve tüm portföy özetini tekrarlamamalı');
assert.match(html,/\/api\/prices\?mode=compact&symbols=/,'Piyasa, favoriler ve alarmlar mevcut toplu servisin kompakt modunu paylaşmalı');
assert.match(pricesApi,/resolveCompact[\s\S]*range=5d&interval=1d[\s\S]*mapWithLimit\(symbols,6/,'Kompakt fiyat modu sınırlı eşzamanlılık ve kısa fiyat aralığı kullanmalı');
assert.match(pricesApi,/getCache\(\{namespace:'ozer-finans-compact-v1'\}\)[\s\S]*compactCacheKey\('quote',symbol\)[\s\S]*ttl:86400/,'Kompakt fiyatlar sembol bazında tek Vercel Runtime Cache kaydı ve son başarılı veri katmanı kullanmalı');
assert.match(pricesApi,/function compactTtlSeconds\(symbol\)[\s\S]*TEFAS-[\s\S]*return 300[\s\S]*ALTIN-[\s\S]*return 60[\s\S]*return 15/,'Sembol önbelleği veri türüne uygun süre kullanmalı');
assert.match(pricesApi,/resolveForexBatch[\s\S]*scanner\.tradingview\.com\/forex\/scan[\s\S]*TradingView Forex toplu/,'Döviz kartları tek sağlayıcı taramasında gruplanmalı');
assert.match(quoteApi,/tradingViewBistBatch[\s\S]*tickers[\s\S]*TradingView BIST toplu[\s\S]*handler\.resolveQuotes=quoteBatch/,'BIST kartları tek sağlayıcı taramasında gruplanmalı');
assert.match(html,/compactUrl='\/api\/prices\?mode=compact[\s\S]*refresh=1[\s\S]*cachedApiJson\(compactUrl/,'Elle yenileme zaman damgalı önbellek anahtarı üretmeden kontrollü yenileme anahtarı kullanmalı');
assert.match(html,/\['desktopChartNav','mobileChartNav','chartTab'\][\s\S]*pointerdown[\s\S]*prewarmCharts/,'Grafik kütüphanesi Grafik düğmesine ilk dokunuşta önden hazırlanmalı');
assert.match(vercelIgnore,/^archive\/$/m,'GitHub sürüm arşivi Vercel çalışma dağıtımına eklenmemeli');
assert.match(html,/\.portfolio-row-head \{ display:grid; grid-template-columns:34px minmax\(0,1fr\) auto 32px;/,'Portföy kartı kompakt silme sütunu kullanmalı');
assert.match(html,/\.portfolio-delete \{[^}]*width:32px; height:32px;[^}]*font-size:\.85rem;/,'Portföy silme düğmesi görsel olarak küçük olmalı');
assert.match(html,/\.portfolio-delete::before \{[^}]*inset:-6px;/,'Küçük portföy silme düğmesinin dokunma alanı 44 piksel kalmalı');
assert.match(html,/className='portfolio-compact-line'[\s\S]*compactLine\.append\(details,profitValue\)/,'Adet, maliyet ve kâr zarar ikinci kompakt satırda bilgi kaybı olmadan gösterilmeli');
assert.match(html,/\.portfolio-row-title strong \{ font-size:1rem; \}/,'Portföy hisse kodu favorilerle aynı puntoda olmalı');
assert.match(html,/\.portfolio-row-title small \{[^}]*font-size:\.75rem; \}/,'Portföy hisse adı favorilerle aynı puntoda olmalı');
assert.match(html,/\.portfolio-current-value \{[^}]*font-size:1\.02rem;/,'Portföy güncel değeri favorilerle aynı puntoda olmalı');
assert.match(html,/\.portfolio-compact-profit \{[^}]*font-size:\.76rem;/,'Portföy kâr zarar değeri favorilerle aynı puntoda olmalı');
assert.match(html,/assetSymbol:primarySymbol\|\|currentSymbol\(\)/,'Ana grafik veri serisi sade balon için hisse kodunu taşımalı');
assert.match(html,/context\.dataset\.assetSymbol\|\|context\.dataset\.label/,'Grafik veri balonu şirketin uzun adı yerine hisse kodunu kullanmalı');
assert.match(html,/\.distribution-chart-wrap \{ position:relative; height:150px;/,'Portföy dağılım halkaları kompakt yükseklikte olmalı');
assert.match(html,/@media \(max-width:700px\)[\s\S]*\.distribution-grid \{ grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/,'İki dağılım grafiği mobilde de yan yana kalmalı');
assert.match(html,/\.distribution-summary:not\(\.expanded\) li:nth-child\(n\+4\)/,'Dağılım özetinde ilk üç kalem dışındakiler başlangıçta gizlenmeli');
assert.match(html,/toggle\.textContent=expanded\?'Daralt':'Tümünü Göster'/,'Dağılım ayrıntıları açılıp daraltılabilmeli');
assert.match(html,/renderDistributionCenter\(allocationCenter,sortedAllocations\)/,'Halka grafiğinin merkezinde en büyük pay gösterilmeli');
assert.match(html,/label\.textContent=items\[0\]\.label/,'Halka grafiğinin merkezinde en büyük paya sahip ürünün adı gösterilmeli');
assert.doesNotMatch(html,/id="themeToggle"/,'Tema düğmesi ekranın üzerinde sabit kalmamalı');
assert.match(html,/priceApiUrl\(symbol,query\)[\s\S]*startsWith\('TEFAS-'\)[\s\S]*\/api\/tefas\?action=price/,'TEFAS fon fiyatları ayrı sağlayıcı işlevine yönlenmeli');
assert.match(html,/function startUnifiedAssetSearch\([\s\S]*\/api\/search\?q=[\s\S]*\/api\/tefas\?action=search/,'Bütün varlık aramaları piyasa ve TEFAS sonuçlarını aşamalı olarak birleştirmeli');
assert.match(html,/function rankSearchResults\(items,query\)[\s\S]*baseSymbol===foldedQuery[\s\S]*Number\(b\.isTefas\)-Number\(a\.isTefas\)/,'Tam TEFAS fon kodu eşleşmesi ilk beş piyasa sonucunun arkasında kaybolmamalı');
assert.match(html,/managerTerms=\[[\s\S]*'AKBANK'[\s\S]*'GARANTI BBVA'[\s\S]*managerIntent[\s\S]*isTefas&&managerIntent\?0/,'Banka adı aramasında fonlar aynı adlı banka hisselerinin önünde gösterilmeli');
assert.match(html,/dripUnsupported=symbol\.startsWith\('ALTIN-'\)\|\|symbol\.startsWith\('TEFAS-'\)/,'TEFAS fonlarında otomatik temettü seçimi kapalı olmalı');
assert.match(tefasApi,/\/api\/funds\/fonFiyatBilgiGetir/,'TEFAS fiyat işlevi yeni resmî fiyat geçmişi uç noktasını kullanmalı');
assert.match(tefasApi,/export const config = \{ runtime: 'edge' \}/,'TEFAS servisi düşük başlangıç gecikmeli Edge çalışma zamanını kullanmalı');
assert.match(tefasApi,/MIRROR_URL = 'https:\/\/fon\.org\.tr'[\s\S]*\/api\/fund-prices\/[\s\S]*Fon\.org\.tr \/ TEFAS/,'Vercel erişim kesintisinde TEFAS kaynaklı açık fiyat geçmişi yedeği kullanılmalı');
assert.match(tefasApi,/\/api\/funds\?search=[\s\S]*async function search\(query\)[\s\S]*officialPost/,'Fon araması açık katalogdan yapılmalı ve resmî TEFAS yedeğini korumalı');
assert.match(tefasApi,/\/api\/funds\/fonUnvanAra/,'TEFAS araması yeni resmî fon arama uç noktasını kullanmalı');
assert.match(tefasApi,/action==='batch-price'[\s\S]*Promise\.all\(codes\.map/,'Çok sayıdaki TEFAS portföy fiyatı tek toplu istekte paralel alınmalı');
assert.match(tefasApi,/s-maxage=900, stale-while-revalidate=86400/,'Günlük TEFAS fiyatları Edge önbelleğinde tekrar kullanılmalı');
assert.match(tefasApi,/requestedStart=Number\(params\.get\('period1'\)\)[\s\S]*requestedMonths[\s\S]*Math\.min\(60,requestedMonths\)[\s\S]*rangeLimited/,'TEFAS resmî yedeği özel tarih aralığını hesaplamalı ve sağlayıcı sınırını bildirmeli');
assert.match(tefasApi,/YLB:'YAPI KREDİ PORTFÖY PARA PİYASASI FONU'[\s\S]*YVD:'YAPI KREDİ PORTFÖY İKİNCİ PARA PİYASASI \(TL\) FONU'[\s\S]*ENR:'QNB PORTFÖY ENPARA PARA PİYASASI \(TL\) FONU'/,'YLB, YVD ve ENR resmî Türkçe adlarıyla korunmalı');
assert.match(html,/Eşleşen ürün bulunamadı\./,'Boş arama sonuçları kullanıcıya görünür şekilde bildirilmeli');
assert.match(html,/Arama servisine ulaşılamadı\./,'Arama kesintisi ürün bulunamamasından ayrılmalı');
assert.match(html,/Fonlar ve hisseler aranıyor…/,'TEFAS yanıtı beklenirken aramanın sürdüğü görünür olmalı');
assert.match(html,/knownTefasFunds=[\s\S]*TEFAS-YLB[\s\S]*TEFAS-YVD[\s\S]*TEFAS-ENR[\s\S]*function knownTefasMatches/,'YLB, YVD ve ENR ağ yanıtı beklenmeden yerel hızlı öneri olarak bulunmalı');
assert.match(html,/function cachedDripResult\(position\)[\s\S]*async function refreshDripResults\(positions\)[\s\S]*async function fetchPortfolioItem\(position\)[\s\S]*dripResult=cachedDripResult\(position\)/,'Portföy fiyat çizimi DRIP ağ isteğini beklememeli ve hazır hesap sonucunu kullanmalı');
assert.doesNotMatch(portfolioPriceLoader,/await fetchDrip|await dripPromise/,'Portföy fiyat yükleyicisi temettü geçmişini beklememeli');
assert.match(html,/const quickFundQuotes=knownTefasMatches\(query\)[\s\S]*showPortfolioSuggestions\(quickFundQuotes,/,'Portföy araması bilinen TEFAS fonlarını anında göstermeli');
assert.ok((html.match(/const quickFundQuotes=knownTefasMatches\(query\)/g)||[]).length>=5,'Grafik, Favoriler, Piyasa, Kıyaslama ve Portföy aramaları aynı hızlı TEFAS eşleşmesini kullanmalı');
assert.match(html,/async function prefetchPortfolioPrices\(positions\)[\s\S]*prefetchPricePayloads\(positions,\{query\}\)/,'Portföy fiyatları tek toplu istekle istemci önbelleğine yerleştirilmeli');
assert.match(pricesApi,/MAX_SYMBOLS=40[\s\S]*mapWithLimit\(symbols,6[\s\S]*results:Object\.fromEntries/,'Toplu fiyat servisi doğrulanmış sembolleri sınırlı eşzamanlılıkla tek yanıtta birleştirmeli');
assert.match(pricesApi,/priceHandler[\s\S]*quoteHandler[\s\S]*goldHandler[\s\S]*tefasHandler/,'Toplu fiyat servisi mevcut sağlayıcı yollarını yeniden kullanmalı');
assert.match(html,/portfolioSnapshotsKey[\s\S]*function renderCachedPortfolioSnapshot\(\)[\s\S]*Son kayıt gösteriliyor; güncel veriler arka planda alınıyor/,'Son başarılı portföy değerleri ekran açılır açılmaz cihazdan gösterilmeli');
assert.match(html,/savePortfolioSnapshot\(\{mode:portfolioMetricsMode,totalValue:[\s\S]*rows:snapshotRows\}\)/,'Başarılı portföy hesaplaması seçili dönemle sonraki hızlı açılış için saklanmalı');
assert.match(html,/id="otherView"[\s\S]*data-theme-choice="light"[\s\S]*data-theme-choice="dark"[\s\S]*data-theme-choice="system"/,'Diğer ekranı Açık, Koyu ve Sistem tema seçeneklerini içermeli');
assert.doesNotMatch(html,/data-theme-choice="(?:ocean|plum|sand|contrast|oled)"/,'Ek renk paleti düğmeleri kaldırılmış olmalı');
assert.match(html,/const themeOptions = \['light','dark','system'\]/,'Tema tercihleri yalnız standart üç seçenekle doğrulanmalı');
assert.match(html,/id="otherView"[\s\S]*id="backupDownload"[\s\S]*id="restoreBackup"/,'Veri yedekleme araçları Diğer ekranında korunmalı');
assert.match(html,/function startRefreshTimers\(\{immediate=false,bypassGap=false\}=\{\}\)[\s\S]*setTimeout\([\s\S]*refreshInterval/,'Otomatik yenileme tek ve çakışmayan zamanlayıcıyla kullanıcı tercihine göre yeniden başlatılmalı');
assert.match(html,/\/api\/prices\?symbols=[\s\S]*prefetchPricePayloads/,'Fiyatlar tek toplu API isteğiyle önceden alınmalı');
assert.doesNotMatch(html,/chartRefreshTimerId|portfolioRefreshTimerId|marketRefreshTimerId/,'Aynı anda çalışan eski çoklu yenileme zamanlayıcıları kaldırılmalı');
assert.match(html,/savedRefreshInterval===null\?15000:Number\(savedRefreshInterval\)/,'Yeni kullanıcılar için otomatik yenileme varsayılan olarak 15 saniye olmalı');
assert.match(html,/themeMedia\.addEventListener\('change'[\s\S]*themePreference==='system'/,'Sistem teması cihaz görünümü değiştiğinde otomatik uygulanmalı');
assert.match(html,/themeColorMeta\.content=resolved==='light'\?'#eef3f8':'#101827'/,'PWA üst çubuğu açık veya koyu temayla eşleşmeli');
assert.match(html,/function ensureChartLibrary\(\)[\s\S]*script\.src='assets\/chart\.umd\.min\.js\?v=4\.4\.4'/,'Chart.js ihtiyaç anında uygulamanın kendi dosyasından yüklenmeli');
assert.match(html,/requestIdleCallback\(prewarmCharts,\{timeout:2500\}\)/,'Chart.js ilk Grafik geçişini hızlandırmak için ana ekran boşta kaldığında hazırlanmalı');
assert.match(html,/let pendingActiveRefresh = false;[\s\S]*if\(bypassGap\)pendingActiveRefresh=true;[\s\S]*queueMicrotask\(\(\)=>runActiveRefresh\(\{leaderRequired:false,bypassGap:true\}\)\)/,'Sekme değişimindeki yenileme, devam eden istekten sonra beklemeden çalıştırılmalı');
assert.doesNotMatch(html,/cdn\.jsdelivr\.net\/npm\/chart\.js/,'Grafikler çalışma anında harici CDN’ye bağlı olmamalı');
assert.ok(chartVendor.length>150000&&/Chart/.test(chartVendor),'Yerel Chart.js paketi eksiksiz görünmeli');
assert.match(html,/rel="apple-touch-icon" sizes="180x180" href="assets\/apple-touch-icon\.png\?v=7\.5"/,'iPhone ana ekranı özel Özer Finans ikonunu kullanmalı');
assert.match(html,/rel="manifest" href="manifest\.webmanifest\?v=7\.5"/,'PWA manifesti sürümlü bağlantıyla yüklenmeli');
assert.equal(manifest.name,'Özer Finans','Manifest uygulamanın tam adını taşımalı');
assert.equal(manifest.display,'standalone','PWA bağımsız uygulama görünümünde açılmalı');
assert.deepEqual(manifest.icons.map(icon=>icon.sizes),['192x192','512x512'],'Manifest standart PWA ikon boyutlarını içermeli');
for(const [file,size] of [['apple-touch-icon.png',180],['icon-192.png',192],['icon-512.png',512]])assert.deepEqual(pngDimensions(fs.readFileSync(path.join(root,'assets',file))),{width:size,height:size},'PWA ikonu doğru ölçüde ve çözülebilir olmalı: '+file);
assert.match(html,/function quotePriceApiUrl\(symbol\)[\s\S]*range=1mo&interval=1d/,'Piyasa ve Favoriler ortak fiyat URL’si kullanmalı');
assert.match(html,/async function fetchCompactQuote\(item,\{force=false\}=\{\}\)[\s\S]*fetchSnapshotQuote\(item\.symbol,\{force\}\)[\s\S]*cachedApiJson\(quotePriceApiUrl\(item\.symbol\),\{force\}\)/,'BIST ve TEFAS güncel fiyatı ortak katmandan, diğer ürünler ortak geçmişten alınmalı');
assert.match(html,/function optionalQuoteNumber\(value\)[\s\S]*value===null\|\|value===undefined\|\|value===''[\s\S]*return Number\.isFinite\(number\)\?number:null/,'Eksik önceki kapanış null değeri yanlışlıkla sıfıra çevrilmemeli');
assert.match(html,/async function fetchFavoriteQuote\(item,\{force=false\}=\{\}\) \{[\s\S]*return fetchCompactQuote\(item,\{force\}\)/,'Favoriler ortak kompakt fiyat katmanını kullanmalı');
assert.match(html,/async function loadMarketSummary\(\{force=false,quotes=null\}=\{\}\)[\s\S]*quotes\|\|await fetchCompactQuotes\(items,\{force\}\)/,'Piyasa özeti favorilerle aynı toplu fiyat katmanını kullanmalı');
assert.match(quoteApi,/'close','change','change_abs'[\s\S]*scanner\.tradingview\.com\/turkey\/scan/,'BIST fiyatı ve günlük değişimi aynı TradingView anlık görüntüsünden gelmeli');
assert.match(quoteApi,/'last_bar_update_time'[\s\S]*yahooSafeFallback\(symbol\)\.catch\(\(\)=>null\)[\s\S]*Math\.min\(lastPriceTime,exchangeTradeTime\)/,'BIST kartı gecikmeli iletim saatini borsadaki gerçek son işlem zamanıyla sınırlandırmalı');
assert.doesNotMatch(quoteApi,/priceType:'delayed_quote'[\s\S]{0,160}asOf:Math\.floor\(Date\.now/,'BIST fiyat zamanı istek anından üretilmemeli');
assert.match(quoteApi,/Promise\.allSettled\(\[mirrorFund\(code\),officialFund\(code\)\]\)[\s\S]*points\.at\(-1\)\.time[\s\S]*priority/,'TEFAS için iki kaynak karşılaştırılıp en yeni tarih ve resmî kaynak önceliği uygulanmalı');
assert.match(quoteApi,/previous=points\.length>1\?points\.at\(-2\):null[\s\S]*missingSessions:/,'BIST yedeği tatil sonrası gerçek önceki fiyat noktasını kullanmalı');
assert.match(html,/priceType==='official_daily'\?'Son resmî · '/,'Fon fiyatının resmî günlük veri olduğu kartta açıkça gösterilmeli');
assert.match(html,/\.favorite-card \{[^}]*position:relative;[^}]*padding:8px 11px 15px;/,'Favori kartı ölçülü biçimde aşağı taşınan fiyat zamanı için yer ayırmalı');
assert.match(html,/\.favorite-market-time \{[^}]*position:absolute;[^}]*right:11px;[^}]*bottom:7px;/,'Fiyat zamanı şirket adı sütununu daraltmadan karta daha yakın konumlanmalı');
assert.match(html,/const inFlightKey=url;[\s\S]*apiInFlight\.has\(inFlightKey\)/,'Zorunlu ve otomatik yenilemede aynı fiyat istekleri birleştirilmeli');
assert.match(html,/function compactQuoteInterval\(symbol,baseInterval=refreshInterval\)[\s\S]*async function fetchCompactQuotes\(items,\{force=false,baseInterval=refreshInterval\}=\{\}\)[\s\S]*\/api\/prices\?mode=compact&symbols=/,'Piyasa, Favoriler ve Alarmlar kompakt toplu isteği paylaşmalı');
assert.match(pricesApi,/MAX_SYMBOLS=40[\s\S]*mapWithLimit\(symbols,6[\s\S]*results:Object\.fromEntries/,'Toplu fiyat API en fazla kırk sembolü kontrollü eşzamanlılıkla işlemeli');
assert.match(html,/function refreshActiveView\([\s\S]*mainView\.classList\.contains\('active'\)[\s\S]*chartView\.classList\.contains\('active'\)[\s\S]*portfolioView\.classList\.contains\('active'\)/,'Yalnız görünür uygulama sayfası otomatik yenilenmeli');
assert.match(html,/function claimPollingLeadership\([\s\S]*refreshLeaderKey[\s\S]*refreshInstanceId/,'Aynı cihazdaki sekmelerden yalnız biri otomatik fiyat sorgulamalı');
assert.match(html,/document\.addEventListener\('visibilitychange'[\s\S]*releasePollingLeadership\(\)[\s\S]*startRefreshTimers\(\{immediate:true\}\)/,'Arka plandaki sayfa sorgulamayı bırakmalı ve dönüşte zamanlayıcı çakışmamalı');
assert.match(html,/let alarmCheckInProgress=false;[\s\S]*async function checkAlarms\(\)[\s\S]*alarmCheckInProgress\|\|activeRefreshInProgress[\s\S]*new Set\(active\.map[\s\S]*fetchCompactQuotes\(items,\{baseInterval:alarmCheckInterval\}\)[\s\S]*finally\s*\{\s*alarmCheckInProgress=false/,'Alarmlar sembolleri tekilleştirerek toplu alınmalı ve aynı anda ikinci denetim başlamamalı');
assert.match(html,/function displaySymbol\(value\)[\s\S]*endsWith\('\.IS'\)\?symbol\.slice\(0,-3\):symbol/,'BIST kodları kullanıcıya .IS eki olmadan gösterilmeli');
assert.match(html,/async function resolveAssetInput\(value\)[\s\S]*symbol\+'\.IS'[\s\S]*exact\|\|bist/,'Ek içermeyen BIST kodu arama sonucundan otomatik çözülmeli');
assert.match(html,/for="favoriteSearch">Favorilere eklenecek hisseyi ara/,'Favori aramasının kalıcı erişilebilir adı olmalı');
assert.match(html,/for="portfolioSymbol">Portföye eklenecek hisseyi ara/,'Portföy aramasının kalıcı erişilebilir adı olmalı');
assert.match(html,/for="benchmarkSearch">Karşılaştırma ölçütü ara/,'Ölçüt aramasının kalıcı erişilebilir adı olmalı');
assert.match(html,/dialog\.addEventListener\('cancel',event=>\{event\.preventDefault\(\);dialog\.close\(\)\}\)/,'Tüm paneller Escape ile kapanmalı');
assert.match(html,/document\.addEventListener\('keydown',event=>\{[\s\S]*event\.key!=='Escape'[\s\S]*dialog\.close\(\)/,'Native cancel üretmeyen tarayıcılarda Escape yedeği bulunmalı');
assert.match(html,/id="backupFileName"/,'Özel Türkçe dosya seçici seçilen dosya adını göstermeli');
assert.match(html,/schemaVersion:3[\s\S]*portfolios:portfolioBooks\.map\(book=>[\s\S]*purchaseDate,dripEnabled,dripTaxRate,dripFractional/,'Yedek dosyası bütün portföyleri, alış tarihlerini ve temettü ayarlarını içermeli');
assert.match(html,/if\(!\[1,2,3\]\.includes\(payload\.schemaVersion\)\)[\s\S]*payload\.schemaVersion>=2[\s\S]*raw\.portfolio/,'Yeni yedek şeması eski tek portföylü yedekleri de kabul etmeli');
assert.match(html,/preferences:\{defaultPortfolioId:[\s\S]*backupReminderDays[\s\S]*lastBackup/,'Yedek dosyası yeni görünüm, portföy, alarm ve hatırlatma tercihlerini içermeli');
assert.match(html,/\.portfolio-book-tabs \{[^}]*flex-wrap:wrap/,'Çok sayıdaki portföy kısayolu yeni satırlara geçebilmeli');
assert.match(html,/function attachPortfolioBookReorder\(tab,book\)[\s\S]*followGhost[\s\S]*persistPortfolioBookOrderFromDom/,'Portföy kısayolları yumuşak takip ve yerleşme animasyonuyla sıralanabilmeli');
assert.match(html,/function applyPreferredCurrency\(value\)[\s\S]*portfolioBooks\.forEach\(book=>\{book\.displayCurrency=baseCurrencyPreference\}\)/,'Tercih edilen para birimi bütün portföylere uygulanmalı');
assert.match(html,/applyPreferredCurrency\(value\)[\s\S]*allPortfolioDisplayCurrency=baseCurrencyPreference==='TRY'\?'TRY':'USD'[\s\S]*localStorage\.setItem\(allPortfolioCurrencyKey,allPortfolioDisplayCurrency\)/,'Tercih menüsü portföy ve toplam alanındaki önceki yerel seçimlerin üzerine yazmalı');
assert.match(html,/valueCurrency=nativeMode\?position\.currency:presentationCurrency/,'Ürünün kendi para birimi seçeneği pozisyon değerlerini dönüştürmemeli');
assert.match(html,/renderCashBalances\(portfolioDisplayCurrency==='NATIVE'\?null:cashDisplayValues,presentationCurrency\)/,'Nakit bakiyeleri aktif portföyün ürün para birimi modunda dönüştürülmemeli');
assert.match(html,/const targetCurrency=portfolioDisplayCurrency==='NATIVE'\?null:portfolioDisplayCurrency[\s\S]*shownCurrency=targetCurrency\|\|item\.currency/,'Temettü tutarları aktif portföyün yerel para birimi seçimine göre gösterilmeli');
assert.match(html,/pastDividends=results\.flatMap\(item=>item\.pastEvents\|\|\[\]\)[\s\S]*Yaklaşan temettü bulunamadı; en son geçmiş temettüler gösteriliyor/,'Yaklaşan temettü yoksa hafif batch yanıtından en yeni geçmiş temettüler gösterilmeli');
assert.match(html,/\.settings-switches \{ display:grid; gap:11px; \}[\s\S]*\.settings-switches \.setting-switch \{ width:100%; display:flex; align-items:center; justify-content:space-between;/,'Bildirim anahtarlarının özel kuralı genel etiket ızgarasını geçersiz kılıp metnin sağında durmalı');
assert.match(html,/\.setting-switch \{ display:flex; align-items:center; justify-content:space-between;[\s\S]*\.setting-switch input \{ flex:0 0 auto;[^}]*margin:0;/,'Bildirim anahtarları açıklamanın doğrudan sağında ve sağ kenara tam yaslı durmalı');
assert.doesNotMatch(html,/id="layoutDensitySelect"/,'Etkisiz yoğunluk seçimi ayarlardan kaldırılmalı');
assert.match(html,/function mergePortfolioBooks\(current,incoming\)[\s\S]*portfolioBooks=mergePortfolioBooks\(portfolioBooks,data\.portfolios\)/,'Birleştirerek geri yükleme portföyleri kimlikleriyle ekleyip güncellemeli');
assert.match(html,/Alım tarihi kayıtlı pozisyonlar:[\s\S]*Temettü yeniden yatırımı açık pozisyonlar:/,'Yedek önizlemesi tarih ve temettü ayarı kapsamını göstermeli');
assert.match(html,/id="portfolioCostCurrency"[\s\S]*id="portfolioPurchaseDate"/,'Portföy maliyet para birimi ve alım tarihi kaydedilebilmeli');
assert.match(html,/function openPortfolioDialog\(position=null,\{choosePortfolio=false\}=\{\}\)[\s\S]*portfolioQuantity\.value = editing\?String\(position\.baseQuantity\?\?position\.quantity\)[\s\S]*portfolioCost\.value = editing\?String\(position\.unitCost\)[\s\S]*portfolioPurchaseDate\.value = editing\?\(position\.purchaseDate\|\|''\)/,'Pozisyon düzenleme penceresi mevcut adet, maliyet ve alış tarihini doldurmalı');
assert.match(html,/const editPosition=\(\)=>\{const saved=portfolio\.find[\s\S]*openPortfolioDialog\(saved\)[\s\S]*row\.addEventListener\('click'/,'Portföy kartına tıklamak düzenleme akışını açmalı');
assert.match(html,/row\.setAttribute\('aria-label',position\.symbol\+' pozisyonunu düzenle'\)/,'Portföy kartı erişilebilir düzenleme etiketi taşımalı');
assert.match(html,/if\(edited\)\{[\s\S]*edited\.quantity=quantity;edited\.baseQuantity=quantity;edited\.unitCost=unitCost;edited\.costCurrency=costCurrency;edited\.purchaseDate=purchaseDate;/,'Düzenleme kaydı yeni adet eklemek yerine mevcut pozisyonu güncellemeli');
assert.match(html,/function removePortfolioWithUndo\(symbol\)[\s\S]*offerUndo[\s\S]*event\.stopPropagation\(\);removePortfolioWithUndo/,'Pozisyon silme kart düzenlemeyi tetiklemeden geri alma sunmalı');
assert.match(html,/historicalUsdRate\(costCurrency,position\.purchaseDate\)/,'Maliyet, alım tarihindeki kurla özet para birimine çevrilmeli');
assert.match(html,/previousTime:previousPoint\.time/,'Günlük portföy hesabı fiyat oluşum saatini önceki kapanış tarihi yerine kullanmamalı');
assert.match(html,/convertedCash=[\s\S]*historicalUsdRate\(balance\.currency,previousDate\)/,'Nakit bakiyenin günlük değişimi önceki işlem günü kurunu kullanmalı');
assert.match(html,/previousPresentationFactor[\s\S]*displayedPrevious=totalPreviousValue\*previousPresentationFactor/,'Dönüştürülmüş portföyün günlük değişimi önceki günün sunum kuruyla hesaplanmalı');
assert.match(html,/Kısmi sonuç gösterilmedi\. Eksik veri/,'Eksik varlıkla performans kıyası sessizce yayınlanmamalı');
assert.match(html,/prepareVisibleRsi\(symbol,points\)/,'Kısa dönem RSI için görünür dönem öncesi veri kullanılmalı');
assert.doesNotMatch(html,/En yeni fiyat:/,'Piyasa özeti başlığında en yeni fiyat etiketi gösterilmemeli');
assert.match(html,/@media \(min-width:761px\) and \(max-width:900px\)/,'Tablet geçişi için ayrı düzen bulunmalı');
assert.match(html,/name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover"/,'Uygulama görünümünde sayfa ölçeği sabitlenmeli');
assert.match(html,/@media \(max-width:760px\)[\s\S]*input,select,textarea \{ font-size:16px !important; \}/,'iOS odak yakınlaştırmasını önlemek için mobil girişler en az 16 px olmalı');
assert.match(html,/\['gesturestart','gesturechange','gestureend'\][\s\S]*event=>event\.preventDefault\(\)[\s\S]*event\.touches\.length>1/,'iOS pinch ve gesture yakınlaştırması engellenmeli');
assert.match(html,/mobileMoreNav'\)\.addEventListener\('click',[\s\S]*openView\('other'\)/,'Mobil Diğer düğmesi sabit ayarlar ekranını açmalı');
assert.match(html,/id="otherAlarmShortcut"[\s\S]*id="otherAlarmCount"/,'Mobil Diğer ekranında fiyat alarmları kısayolu ve aktif alarm sayısı bulunmalı');
assert.match(html,/function syncPortfolioEmptyState\(\)[\s\S]*portfolioEmptyStart\.hidden/,'Boş portföyde uzun analiz alanları tek başlangıç kartına daraltılmalı');
assert.match(html,/allPortfolioHead\.hidden=portfolioBooks\.length<2/,'Birleşik toplam kartı yalnız birden fazla portföy varken gösterilmeli');
assert.match(html,/function removeFavoriteWithUndo[\s\S]*function removePortfolioWithUndo[\s\S]*function removeCashWithUndo/,'Favori, pozisyon ve nakit silme işlemlerinin geri alma akışı olmalı');
assert.match(html,/function removeActivePortfolio\(\)[\s\S]*offerUndo\('\“'\+current\.name\+'” portföyü silindi\.'[\s\S]*portfolioBooks\.splice\(Math\.min\(index,portfolioBooks\.length\),0,current\)/,'Silinen bağımsız portföy bütün içeriği ve eski sırasıyla geri alınabilmeli');
assert.match(html,/setAttribute\('aria-pressed',String\(active\)\)/,'Seçili grafik ve karşılaştırma dönemleri erişilebilir durumda bildirilmelı');
assert.doesNotMatch(html,/className='market-card-status'/,'Piyasa kartlarında tarih, saat ve gecikme için ek görünür satır olmamalı');
assert.match(html,/\.settings-grid \{ display:grid; grid-template-columns:1fr;/,'Diğer ekranındaki ayar kartları yatay satırlar halinde sıralanmalı');
assert.match(html,/\.settings-horizontal \{ display:grid; grid-template-columns:minmax\(210px,\.8fr\) minmax\(320px,1\.2fr\)/,'İlk dört ayar kartının içeriği masaüstünde yatay yerleşmeli');
assert.match(html,/\.setting-switch \{[^}]*padding:0; border:0;/,'Fiyat alarmı anahtarı ikinci bir kutu içine alınmamalı');
assert.ok(html.indexOf('id="backupTitle"')<html.indexOf('id="helpTitle"'),'Yardım ve uygulama bilgileri Veri Yedekleme bölümünden sonra gelmeli');

assert.match(html,/id="authGate"[\s\S]*id="authLoginForm"[\s\S]*id="authLocalContinue"/,'Açılış ekranında e-posta girişi ve yerel devam seçenekleri bulunmalı');
assert.match(html,/id="authRegisterForm"[\s\S]*id="authBootstrapForm"/,'Davetli kayıt ve ilk yönetici kurulum formları bulunmalı');
assert.match(html,/id="adminUsersCard"[\s\S]*id="createInvite"[\s\S]*id="inviteResult"/,'Yönetici için kullanıcı davet ekranı bulunmalı');
assert.match(html,/assets\/storage-events\.js\?v=7\.5[\s\S]*assets\/auth-account\.js\?v=7\.5\.0/,'Yerel değişiklik gözlemi yeni hesap istemcisinden önce yüklenmeli');
assert.match(authAccount,/credentials: 'same-origin'[\s\S]*\/api\/account\?action=login[\s\S]*\/api\/account\?action=register/,'İstemci güvenli çerezle birleşik giriş ve davetli kayıt API’sini kullanmalı');
assert.ok(fs.readdirSync(path.join(root,'api')).filter(name=>name.endsWith('.js')).length<=12,'Hobby planı için sunucu fonksiyonu sayısı 12’yi aşmamalı');
assert.match(authAccount,/localStorage\.setItem\(GUEST_BACKUP_KEY[\s\S]*function restoreGuestSnapshot/,'Misafir verisi hesap verisinden ayrı korunmalı');
assert.match(authAccount,/expectedVersion: state\.version[\s\S]*error\.status === 409/,'Bulut senkronizasyonu sürüm çakışmalarını sessizce ezmemeli');
assert.match(authStore,/createCipheriv\('aes-256-gcm'[\s\S]*createDecipheriv\('aes-256-gcm'/,'Kullanıcı kayıtları AES-GCM ile şifrelenmeli');
assert.match(authStore,/scrypt\(password[\s\S]*N: 32768[\s\S]*timingSafeEqual/,'Şifreler güçlü scrypt parametreleriyle doğrulanmalı');
assert.match(authStore,/HttpOnly; Secure; SameSite=Lax/,'Oturum çerezi istemci betiklerine kapalı ve güvenli olmalı');
assert.match(authLoginApi,/login-attempt:[\s\S]*attempts > 10/,'Giriş denemeleri oran sınırına sahip olmalı');
assert.match(authRegisterApi,/invite:[\s\S]*await saveUser[\s\S]*DEL/,'Davet kodu yalnız bir kez kullanılmalı');
assert.match(adminInvitesApi,/requireUser\(req, res, 'admin'\)[\s\S]*EX', 86400/,'Davet yalnız yönetici tarafından ve 24 saatlik oluşturulmalı');
assert.match(userStateApi,/requireUser\(req, res\)[\s\S]*encryptJson\(record\)/,'Kullanıcı verisi oturumla ayrılmalı ve şifrelenmeli');
assert.doesNotMatch(html,/CLERK_SECRET_KEY|DATABASE_URL=|NEXT_PUBLIC_CLERK/,'Sunucu sırları HTML içine gömülmemeli');

assert.match(html,/<title>Özer Finans v7\.5 Önizleme<\/title>/,'Önizleme sürümü başlıkta açıkça belirtilmeli');
console.log('Özer Finans v7.5 önizleme regresyon testleri başarılı.');
